import type { VocabItem } from './types'

/**
 * The most common Romanian words, hand-curated from the top of the frequency list
 * (src/content/generated/vocab-top10k.json): diacritic-less subtitle duplicates, names, English
 * leftovers, swearing and the film-subtitle violence are left out, and every entry has a short
 * English meaning. Sorted by frequency. Used by the Common words deck for recognition practice.
 */
export const coreWords: VocabItem[] = [
  { id: 'v-de', rank: 1, word: 'de', corpusCount: 7913087, translation: 'of, from, since' },
  { id: 'v-nu', rank: 2, word: 'nu', corpusCount: 7276949, translation: 'no, not' },
  { id: 'v-să', rank: 3, word: 'să', corpusCount: 6284148, translation: '(that) — the "to" bridge: vreau să…' },
  { id: 'v-o', rank: 4, word: 'o', corpusCount: 3849365, translation: 'a (o-word); her; it' },
  { id: 'v-și', rank: 5, word: 'și', corpusCount: 3670602, translation: 'and; also, too' },
  { id: 'v-e', rank: 6, word: 'e', corpusCount: 3612874, translation: 'is' },
  { id: 'v-în', rank: 7, word: 'în', corpusCount: 3604069, translation: 'in, into' },
  { id: 'v-ce', rank: 8, word: 'ce', corpusCount: 3600269, translation: 'what' },
  { id: 'v-că', rank: 9, word: 'că', corpusCount: 3421716, translation: 'that; because' },
  { id: 'v-la', rank: 10, word: 'la', corpusCount: 3255497, translation: 'at, to' },
  { id: 'v-a', rank: 11, word: 'a', corpusCount: 3111499, translation: 'has; to (before a verb)' },
  { id: 'v-cu', rank: 12, word: 'cu', corpusCount: 2751988, translation: 'with' },
  { id: 'v-pe', rank: 13, word: 'pe', corpusCount: 2713969, translation: 'on; (the person tag)' },
  { id: 'v-am', rank: 14, word: 'am', corpusCount: 2637983, translation: 'I have; we have' },
  { id: 'v-un', rank: 15, word: 'un', corpusCount: 2535624, translation: 'a (un-word)' },
  { id: 'v-mai', rank: 16, word: 'mai', corpusCount: 2305194, translation: 'more; still; again' },
  { id: 'v-asta', rank: 17, word: 'asta', corpusCount: 2115588, translation: 'this, that (thing)' },
  { id: 'v-pentru', rank: 18, word: 'pentru', corpusCount: 1922223, translation: 'for' },
  { id: 'v-sunt', rank: 19, word: 'sunt', corpusCount: 1709982, translation: 'I am; they are' },
  { id: 'v-ai', rank: 20, word: 'ai', corpusCount: 1686731, translation: 'you have' },
  { id: 'v-este', rank: 21, word: 'este', corpusCount: 1677844, translation: 'is' },
  { id: 'v-te', rank: 22, word: 'te', corpusCount: 1667085, translation: 'you (object)' },
  { id: 'v-da', rank: 24, word: 'da', corpusCount: 1620510, translation: 'yes' },
  { id: 'v-bine', rank: 25, word: 'bine', corpusCount: 1612599, translation: 'well, fine, OK' },
  { id: 'v-dar', rank: 26, word: 'dar', corpusCount: 1497752, translation: 'but' },
  { id: 'v-se', rank: 27, word: 'se', corpusCount: 1393550, translation: 'himself, herself; one (people in general)' },
  { id: 'v-din', rank: 28, word: 'din', corpusCount: 1352938, translation: 'from, out of' },
  { id: 'v-care', rank: 29, word: 'care', corpusCount: 1328809, translation: 'which, who' },
  { id: 'v-fost', rank: 30, word: 'fost', corpusCount: 1320415, translation: 'been; was (am fost)' },
  { id: 'v-fi', rank: 31, word: 'fi', corpusCount: 1247259, translation: 'be' },
  { id: 'v-mă', rank: 32, word: 'mă', corpusCount: 1234381, translation: 'me; myself' },
  { id: 'v-eu', rank: 34, word: 'eu', corpusCount: 1173224, translation: 'I' },
  { id: 'v-aici', rank: 35, word: 'aici', corpusCount: 1155607, translation: 'here' },
  { id: 'v-dacă', rank: 36, word: 'dacă', corpusCount: 1008117, translation: 'if, whether' },
  { id: 'v-trebuie', rank: 37, word: 'trebuie', corpusCount: 947062, translation: 'must, have to' },
  { id: 'v-va', rank: 39, word: 'va', corpusCount: 896045, translation: 'will (he / she will)' },
  { id: 'v-cum', rank: 40, word: 'cum', corpusCount: 870738, translation: 'how' },
  { id: 'v-tu', rank: 41, word: 'tu', corpusCount: 837169, translation: 'you' },
  { id: 'v-acum', rank: 42, word: 'acum', corpusCount: 828072, translation: 'now' },
  { id: 'v-așa', rank: 43, word: 'așa', corpusCount: 821130, translation: 'so, like this' },
  { id: 'v-ești', rank: 44, word: 'ești', corpusCount: 752950, translation: 'you are' },
  { id: 'v-ceva', rank: 45, word: 'ceva', corpusCount: 748581, translation: 'something' },
  { id: 'v-ar', rank: 46, word: 'ar', corpusCount: 743024, translation: 'would (he / she / they)' },
  { id: 'v-lui', rank: 47, word: 'lui', corpusCount: 737281, translation: 'his; to him' },
  { id: 'v-el', rank: 48, word: 'el', corpusCount: 730725, translation: 'he' },
  { id: 'v-când', rank: 49, word: 'când', corpusCount: 713899, translation: 'when' },
  { id: 'v-doar', rank: 50, word: 'doar', corpusCount: 704431, translation: 'only, just' },
  { id: 'v-ne', rank: 51, word: 'ne', corpusCount: 683500, translation: 'us; ourselves' },
  { id: 'v-ei', rank: 52, word: 'ei', corpusCount: 662013, translation: 'they; her (hers); to her' },
  { id: 'v-mine', rank: 53, word: 'mine', corpusCount: 658000, translation: 'me (after cu, pentru…)' },
  { id: 'v-tine', rank: 54, word: 'tine', corpusCount: 652452, translation: 'you (after cu, pentru…)' },
  { id: 'v-poate', rank: 55, word: 'poate', corpusCount: 628013, translation: 'maybe; he / she can' },
  { id: 'v-pot', rank: 56, word: 'pot', corpusCount: 619524, translation: 'I can' },
  { id: 'v-cred', rank: 57, word: 'cred', corpusCount: 616093, translation: 'I think, I believe' },
  { id: 'v-voi', rank: 58, word: 'voi', corpusCount: 607539, translation: 'you (all); I will' },
  { id: 'v-face', rank: 59, word: 'face', corpusCount: 606212, translation: 'does, makes' },
  { id: 'v-îmi', rank: 60, word: 'îmi', corpusCount: 601290, translation: 'to me' },
  { id: 'v-știu', rank: 61, word: 'știu', corpusCount: 584670, translation: 'I know' },
  { id: 'v-au', rank: 62, word: 'au', corpusCount: 576751, translation: 'they have' },
  { id: 'v-mea', rank: 63, word: 'mea', corpusCount: 563022, translation: 'my (o-word)' },
  { id: 'v-spus', rank: 64, word: 'spus', corpusCount: 546084, translation: 'said, told' },
  { id: 'v-unde', rank: 65, word: 'unde', corpusCount: 537919, translation: 'where' },
  { id: 'v-meu', rank: 66, word: 'meu', corpusCount: 507884, translation: 'my (un-word)' },
  { id: 'v-vă', rank: 67, word: 'vă', corpusCount: 500655, translation: 'you all (object); to you all' },
  { id: 'v-vreau', rank: 68, word: 'vreau', corpusCount: 492320, translation: 'I want' },
  { id: 'v-mult', rank: 69, word: 'mult', corpusCount: 489754, translation: 'much, a lot' },
  { id: 'v-ea', rank: 70, word: 'ea', corpusCount: 485055, translation: 'she' },
  { id: 'v-vrei', rank: 71, word: 'vrei', corpusCount: 482138, translation: 'you want' },
  { id: 'v-despre', rank: 72, word: 'despre', corpusCount: 474509, translation: 'about' },
  { id: 'v-tot', rank: 73, word: 'tot', corpusCount: 457459, translation: 'all, everything; still' },
  { id: 'v-foarte', rank: 75, word: 'foarte', corpusCount: 454839, translation: 'very' },
  { id: 'v-sau', rank: 76, word: 'sau', corpusCount: 454263, translation: 'or' },
  { id: 'v-pare', rank: 77, word: 'pare', corpusCount: 451657, translation: 'seems' },
  { id: 'v-acolo', rank: 78, word: 'acolo', corpusCount: 444864, translation: 'there' },
  { id: 'v-chiar', rank: 79, word: 'chiar', corpusCount: 442895, translation: 'really; even; right (now)' },
  { id: 'v-bună', rank: 80, word: 'bună', corpusCount: 432975, translation: 'good (o-word); hi' },
  { id: 'v-noi', rank: 81, word: 'noi', corpusCount: 427126, translation: 'we' },
  { id: 'v-era', rank: 82, word: 'era', corpusCount: 426743, translation: 'was' },
  { id: 'v-ta', rank: 83, word: 'ta', corpusCount: 420307, translation: 'your (o-word)' },
  { id: 'v-nimic', rank: 84, word: 'nimic', corpusCount: 414158, translation: 'nothing' },
  { id: 'v-faci', rank: 85, word: 'faci', corpusCount: 411987, translation: 'you do' },
  { id: 'v-are', rank: 86, word: 'are', corpusCount: 409323, translation: 'has' },
  { id: 'v-știi', rank: 87, word: 'știi', corpusCount: 407247, translation: 'you know' },
  { id: 'v-făcut', rank: 88, word: 'făcut', corpusCount: 400297, translation: 'done, made' },
  { id: 'v-cine', rank: 89, word: 'cine', corpusCount: 392912, translation: 'who' },
  { id: 'v-nici', rank: 90, word: 'nici', corpusCount: 390297, translation: 'not even; neither' },
  { id: 'v-putea', rank: 91, word: 'putea', corpusCount: 378835, translation: 'be able to; could' },
  { id: 'v-fac', rank: 92, word: 'fac', corpusCount: 367779, translation: 'I do, I make' },
  { id: 'v-fie', rank: 93, word: 'fie', corpusCount: 354849, translation: 'be (să fie)' },
  { id: 'v-nevoie', rank: 95, word: 'nevoie', corpusCount: 347569, translation: 'need' },
  { id: 'v-rău', rank: 96, word: 'rău', corpusCount: 346739, translation: 'bad, badly' },
  { id: 'v-atunci', rank: 97, word: 'atunci', corpusCount: 330328, translation: 'then' },
  { id: 'v-îți', rank: 98, word: 'îți', corpusCount: 325043, translation: 'to you' },
  { id: 'v-timp', rank: 99, word: 'timp', corpusCount: 317070, translation: 'time' },
  { id: 'v-poți', rank: 100, word: 'poți', corpusCount: 315069, translation: 'you can' },
  { id: 'v-tău', rank: 101, word: 'tău', corpusCount: 314675, translation: 'your (un-word)' },
  { id: 'v-rog', rank: 102, word: 'rog', corpusCount: 312230, translation: '(te rog) please — "I ask"' },
  { id: 'v-spun', rank: 103, word: 'spun', corpusCount: 312164, translation: 'I say, I tell' },
  { id: 'v-mulțumesc', rank: 104, word: 'mulțumesc', corpusCount: 302446, translation: 'thank you' },
  { id: 'v-avem', rank: 105, word: 'avem', corpusCount: 300910, translation: 'we have' },
  { id: 'v-spune', rank: 106, word: 'spune', corpusCount: 300633, translation: 'says; tell!' },
  { id: 'v-îl', rank: 107, word: 'îl', corpusCount: 297154, translation: 'him; it (un-word)' },
  { id: 'v-al', rank: 108, word: 'al', corpusCount: 295549, translation: 'of — the possessive linker' },
  { id: 'v-le', rank: 109, word: 'le', corpusCount: 293824, translation: 'them; to them' },
  { id: 'v-prea', rank: 110, word: 'prea', corpusCount: 290884, translation: 'too' },
  { id: 'v-după', rank: 111, word: 'după', corpusCount: 289204, translation: 'after' },
  { id: 'v-deci', rank: 112, word: 'deci', corpusCount: 285063, translation: 'so' },
  { id: 'v-cineva', rank: 113, word: 'cineva', corpusCount: 284233, translation: 'someone' },
  { id: 'v-vom', rank: 114, word: 'vom', corpusCount: 282337, translation: 'we will' },
  { id: 'v-acest', rank: 115, word: 'acest', corpusCount: 282288, translation: 'this (formal)' },
  { id: 'v-toate', rank: 116, word: 'toate', corpusCount: 272453, translation: 'all (o-plural)' },
  { id: 'v-ani', rank: 117, word: 'ani', corpusCount: 269622, translation: 'years' },
  { id: 'v-cel', rank: 119, word: 'cel', corpusCount: 263203, translation: 'the one; (cel mai) the most' },
  { id: 'v-suntem', rank: 120, word: 'suntem', corpusCount: 262233, translation: 'we are' },
  { id: 'v-vei', rank: 121, word: 'vei', corpusCount: 262088, translation: 'you will' },
  { id: 'v-sigur', rank: 122, word: 'sigur', corpusCount: 261209, translation: 'sure, of course' },
  { id: 'v-bun', rank: 123, word: 'bun', corpusCount: 259567, translation: 'good' },
  { id: 'v-vrea', rank: 124, word: 'vrea', corpusCount: 256390, translation: 'wants' },
  { id: 'v-vor', rank: 125, word: 'vor', corpusCount: 253521, translation: 'they want; they will' },
  { id: 'v-îi', rank: 126, word: 'îi', corpusCount: 252705, translation: 'to him / her; them' },
  { id: 'v-haide', rank: 127, word: 'haide', corpusCount: 252609, translation: 'come on' },
  { id: 'v-iar', rank: 128, word: 'iar', corpusCount: 250228, translation: 'again; and (whereas)' },
  { id: 'v-mare', rank: 129, word: 'mare', corpusCount: 249680, translation: 'big; sea' },
  { id: 'v-până', rank: 130, word: 'până', corpusCount: 248985, translation: 'until' },
  { id: 'v-cât', rank: 131, word: 'cât', corpusCount: 248101, translation: 'how much' },
  { id: 'v-crezi', rank: 132, word: 'crezi', corpusCount: 247195, translation: 'you think' },
  { id: 'v-încă', rank: 133, word: 'încă', corpusCount: 238215, translation: 'still, yet' },
  { id: 'v-stai', rank: 134, word: 'stai', corpusCount: 238054, translation: 'wait; stay' },
  { id: 'v-ăsta', rank: 135, word: 'ăsta', corpusCount: 237674, translation: 'this one' },
  { id: 'v-avea', rank: 136, word: 'avea', corpusCount: 235751, translation: 'have; had' },
  { id: 'v-totul', rank: 137, word: 'totul', corpusCount: 234327, translation: 'everything' },
  { id: 'v-spui', rank: 138, word: 'spui', corpusCount: 233229, translation: 'you say' },
  { id: 'v-venit', rank: 139, word: 'venit', corpusCount: 231838, translation: 'come (have come)' },
  { id: 'v-atât', rank: 140, word: 'atât', corpusCount: 226207, translation: 'so much, that much' },
  { id: 'v-avut', rank: 141, word: 'avut', corpusCount: 225949, translation: 'had' },
  { id: 'v-văzut', rank: 143, word: 'văzut', corpusCount: 222437, translation: 'seen' },
  { id: 'v-aș', rank: 145, word: 'aș', corpusCount: 217718, translation: 'I would' },
  { id: 'v-fel', rank: 146, word: 'fel', corpusCount: 216925, translation: 'kind, way' },
  { id: 'v-putem', rank: 147, word: 'putem', corpusCount: 214105, translation: 'we can' },
  { id: 'v-lucru', rank: 149, word: 'lucru', corpusCount: 209597, translation: 'thing' },
  { id: 'v-ceea', rank: 150, word: 'ceea', corpusCount: 208209, translation: '(ceea ce) what, that which' },
  { id: 'v-fără', rank: 151, word: 'fără', corpusCount: 205377, translation: 'without' },
  { id: 'v-place', rank: 152, word: 'place', corpusCount: 204837, translation: 'pleases (îmi place — I like)' },
  { id: 'v-mama', rank: 153, word: 'mama', corpusCount: 203477, translation: 'Mum; the mother' },
  { id: 'v-domnule', rank: 154, word: 'domnule', corpusCount: 201935, translation: 'sir' },
  { id: 'v-decât', rank: 155, word: 'decât', corpusCount: 200145, translation: 'than; only' },
  { id: 'v-regulă', rank: 157, word: 'regulă', corpusCount: 195644, translation: 'rule (în regulă — OK)' },
  { id: 'v-niciodată', rank: 158, word: 'niciodată', corpusCount: 192681, translation: 'never' },
  { id: 'v-puțin', rank: 159, word: 'puțin', corpusCount: 191915, translation: 'a little' },
  { id: 'v-prin', rank: 160, word: 'prin', corpusCount: 186595, translation: 'through' },
  { id: 'v-mergem', rank: 161, word: 'mergem', corpusCount: 183953, translation: 'we go' },
  { id: 'v-văd', rank: 162, word: 'văd', corpusCount: 183487, translation: 'I see' },
  { id: 'v-înainte', rank: 163, word: 'înainte', corpusCount: 183083, translation: 'before; forward' },
  { id: 'v-uite', rank: 164, word: 'uite', corpusCount: 179797, translation: 'look!' },
  { id: 'v-unul', rank: 165, word: 'unul', corpusCount: 179449, translation: 'one' },
  { id: 'v-nimeni', rank: 166, word: 'nimeni', corpusCount: 178088, translation: 'nobody' },
  { id: 'v-loc', rank: 167, word: 'loc', corpusCount: 177005, translation: 'place, room' },
  { id: 'v-hai', rank: 168, word: 'hai', corpusCount: 176056, translation: 'come on; let\'s' },
  { id: 'v-vezi', rank: 169, word: 'vezi', corpusCount: 175396, translation: 'you see' },
  { id: 'v-fii', rank: 170, word: 'fii', corpusCount: 174917, translation: 'be! (imperative)' },
  { id: 'v-dat', rank: 171, word: 'dat', corpusCount: 173427, translation: 'given' },
  { id: 'v-toată', rank: 172, word: 'toată', corpusCount: 172881, translation: 'all, the whole (o-word)' },
  { id: 'v-apoi', rank: 174, word: 'apoi', corpusCount: 171894, translation: 'then, afterwards' },
  { id: 'v-întâmplat', rank: 175, word: 'întâmplat', corpusCount: 171597, translation: 'happened' },
  { id: 'v-oameni', rank: 177, word: 'oameni', corpusCount: 166803, translation: 'people' },
  { id: 'v-toți', rank: 178, word: 'toți', corpusCount: 165681, translation: 'all, everyone' },
  { id: 'v-facem', rank: 179, word: 'facem', corpusCount: 165490, translation: 'we do' },
  { id: 'v-nou', rank: 180, word: 'nou', corpusCount: 164956, translation: 'new' },
  { id: 'v-ia', rank: 181, word: 'ia', corpusCount: 164194, translation: 'take!' },
  { id: 'v-multe', rank: 182, word: 'multe', corpusCount: 160468, translation: 'many (o-plural)' },
  { id: 'v-zi', rank: 183, word: 'zi', corpusCount: 160443, translation: 'day' },
  { id: 'v-acasă', rank: 184, word: 'acasă', corpusCount: 159899, translation: '(at) home' },
  { id: 'v-două', rank: 185, word: 'două', corpusCount: 157929, translation: 'two (o-words)' },
  { id: 'v-lumea', rank: 186, word: 'lumea', corpusCount: 156929, translation: 'the world; people' },
  { id: 'v-jos', rank: 187, word: 'jos', corpusCount: 156411, translation: 'down' },
  { id: 'v-timpul', rank: 188, word: 'timpul', corpusCount: 152442, translation: 'the time' },
  { id: 'v-ați', rank: 189, word: 'ați', corpusCount: 151916, translation: 'you (all) have' },
  { id: 'v-niște', rank: 190, word: 'niște', corpusCount: 148460, translation: 'some' },
  { id: 'v-doi', rank: 191, word: 'doi', corpusCount: 147526, translation: 'two' },
  { id: 'v-orice', rank: 192, word: 'orice', corpusCount: 147379, translation: 'anything' },
  { id: 'v-auzit', rank: 193, word: 'auzit', corpusCount: 147023, translation: 'heard' },
  { id: 'v-astea', rank: 195, word: 'astea', corpusCount: 146543, translation: 'these' },
  { id: 'v-aia', rank: 196, word: 'aia', corpusCount: 145886, translation: 'that one (o)' },
  { id: 'v-fiecare', rank: 197, word: 'fiecare', corpusCount: 145862, translation: 'each, every' },
  { id: 'v-luat', rank: 199, word: 'luat', corpusCount: 144544, translation: 'taken' },
  { id: 'v-peste', rank: 200, word: 'peste', corpusCount: 144103, translation: 'over; in (time)' },
  { id: 'v-fiu', rank: 201, word: 'fiu', corpusCount: 142077, translation: 'son; be (să fiu)' },
  { id: 'v-vrut', rank: 202, word: 'vrut', corpusCount: 140288, translation: 'wanted' },
  { id: 'v-trei', rank: 203, word: 'trei', corpusCount: 139140, translation: 'three' },
  { id: 'v-înapoi', rank: 204, word: 'înapoi', corpusCount: 138895, translation: 'back' },
  { id: 'v-această', rank: 205, word: 'această', corpusCount: 138083, translation: 'this (formal, o)' },
  { id: 'v-lor', rank: 206, word: 'lor', corpusCount: 137117, translation: 'their; to them' },
  { id: 'v-numele', rank: 207, word: 'numele', corpusCount: 136596, translation: 'the name' },
  { id: 'v-cea', rank: 209, word: 'cea', corpusCount: 135457, translation: 'the one (o); (cea mai) the most' },
  { id: 'v-dintre', rank: 210, word: 'dintre', corpusCount: 135231, translation: 'among, of' },
  { id: 'v-merge', rank: 211, word: 'merge', corpusCount: 134934, translation: 'goes; works' },
  { id: 'v-om', rank: 212, word: 'om', corpusCount: 134583, translation: 'person, man' },
  { id: 'v-găsit', rank: 213, word: 'găsit', corpusCount: 132248, translation: 'found' },
  { id: 'v-doamne', rank: 214, word: 'Doamne', corpusCount: 131937, translation: 'Lord! (Doamne ajută)' },
  { id: 'v-viața', rank: 215, word: 'viața', corpusCount: 131878, translation: 'life' },
  { id: 'v-cei', rank: 216, word: 'cei', corpusCount: 131294, translation: 'the ones' },
  { id: 'v-mele', rank: 217, word: 'mele', corpusCount: 126700, translation: 'my (o-plural)' },
  { id: 'v-duc', rank: 218, word: 'duc', corpusCount: 124778, translation: 'I take (someone); (mă duc) I go' },
  { id: 'v-ziua', rank: 219, word: 'ziua', corpusCount: 122861, translation: 'the day; birthday' },
  { id: 'v-serios', rank: 220, word: 'serios', corpusCount: 122829, translation: 'seriously; really?' },
  { id: 'v-deja', rank: 222, word: 'deja', corpusCount: 122651, translation: 'already' },
  { id: 'v-parte', rank: 223, word: 'parte', corpusCount: 122328, translation: 'part, side' },
  { id: 'v-dată', rank: 224, word: 'dată', corpusCount: 120614, translation: 'time (o dată — once); date' },
  { id: 'v-gata', rank: 225, word: 'gata', corpusCount: 120593, translation: 'ready; done; enough!' },
  { id: 'v-câteva', rank: 226, word: 'câteva', corpusCount: 119352, translation: 'a few (o)' },
  { id: 'v-vino', rank: 227, word: 'vino', corpusCount: 118770, translation: 'come!' },
  { id: 'v-vedem', rank: 228, word: 'vedem', corpusCount: 117735, translation: 'we see' },
  { id: 'v-destul', rank: 229, word: 'destul', corpusCount: 117590, translation: 'enough' },
  { id: 'v-bani', rank: 230, word: 'bani', corpusCount: 117304, translation: 'money' },
  { id: 'v-vorbesc', rank: 231, word: 'vorbesc', corpusCount: 115806, translation: 'I speak' },
  { id: 'v-numai', rank: 233, word: 'numai', corpusCount: 115700, translation: 'only' },
  { id: 'v-aproape', rank: 234, word: 'aproape', corpusCount: 115317, translation: 'near; almost' },
  { id: 'v-dau', rank: 235, word: 'dau', corpusCount: 114730, translation: 'I give' },
  { id: 'v-una', rank: 236, word: 'una', corpusCount: 113701, translation: 'one (o)' },
  { id: 'v-zis', rank: 237, word: 'zis', corpusCount: 113151, translation: 'said' },
  { id: 'v-tatăl', rank: 238, word: 'tatăl', corpusCount: 113109, translation: 'the father' },
  { id: 'v-înseamnă', rank: 239, word: 'înseamnă', corpusCount: 112689, translation: 'means' },
  { id: 'v-eram', rank: 240, word: 'eram', corpusCount: 112033, translation: 'I was' },
  { id: 'v-afară', rank: 241, word: 'afară', corpusCount: 111565, translation: 'outside' },
  { id: 'v-vin', rank: 242, word: 'vin', corpusCount: 111261, translation: 'I come; wine' },
  { id: 'v-există', rank: 243, word: 'există', corpusCount: 110338, translation: 'exists, there is' },
  { id: 'v-întâmplă', rank: 244, word: 'întâmplă', corpusCount: 110196, translation: 'happens' },
  { id: 'v-nostru', rank: 245, word: 'nostru', corpusCount: 110178, translation: 'our' },
  { id: 'v-adevărat', rank: 246, word: 'adevărat', corpusCount: 109767, translation: 'true' },
  { id: 'v-scuze', rank: 247, word: 'scuze', corpusCount: 109757, translation: 'sorry' },
  { id: 'v-sunteți', rank: 248, word: 'sunteți', corpusCount: 109743, translation: 'you (all) are' },
  { id: 'v-cam', rank: 249, word: 'cam', corpusCount: 109663, translation: 'rather, a bit; about' },
  { id: 'v-locul', rank: 250, word: 'locul', corpusCount: 109402, translation: 'the place' },
  { id: 'v-știe', rank: 251, word: 'știe', corpusCount: 109197, translation: 'knows' },
  { id: 'v-noastră', rank: 252, word: 'noastră', corpusCount: 109050, translation: 'our (o)' },
  { id: 'v-vine', rank: 253, word: 'vine', corpusCount: 108329, translation: 'comes' },
  { id: 'v-ori', rank: 254, word: 'ori', corpusCount: 107538, translation: 'or; times (de două ori)' },
  { id: 'v-repede', rank: 255, word: 'repede', corpusCount: 107447, translation: 'quickly' },
  { id: 'v-fapt', rank: 256, word: 'fapt', corpusCount: 106830, translation: 'fact (de fapt — actually)' },
  { id: 'v-grijă', rank: 257, word: 'grijă', corpusCount: 106574, translation: 'care (ai grijă — be careful)' },
  { id: 'v-acesta', rank: 258, word: 'acesta', corpusCount: 105887, translation: 'this one (formal)' },
  { id: 'v-probabil', rank: 259, word: 'probabil', corpusCount: 105843, translation: 'probably' },
  { id: 'v-prima', rank: 260, word: 'prima', corpusCount: 105271, translation: 'the first (o)' },
  { id: 'v-tale', rank: 261, word: 'tale', corpusCount: 104661, translation: 'your (o-plural)' },
  { id: 'v-putut', rank: 262, word: 'putut', corpusCount: 104254, translation: 'been able' },
  { id: 'v-exact', rank: 263, word: 'exact', corpusCount: 103788, translation: 'exactly' },
  { id: 'v-ajuns', rank: 264, word: 'ajuns', corpusCount: 103749, translation: 'arrived' },
  { id: 'v-casa', rank: 265, word: 'casa', corpusCount: 103656, translation: 'the house; home' },
  { id: 'v-singur', rank: 266, word: 'singur', corpusCount: 103631, translation: 'alone' },
  { id: 'v-lucruri', rank: 267, word: 'lucruri', corpusCount: 103335, translation: 'things' },
  { id: 'v-simt', rank: 268, word: 'simt', corpusCount: 101474, translation: 'I feel' },
  { id: 'v-dreptate', rank: 269, word: 'dreptate', corpusCount: 100366, translation: 'rightness (ai dreptate — you\'re right)' },
  { id: 'v-noapte', rank: 270, word: 'noapte', corpusCount: 99865, translation: 'night' },
  { id: 'v-trecut', rank: 272, word: 'trecut', corpusCount: 99129, translation: 'passed; the past' },
  { id: 'v-fata', rank: 273, word: 'fata', corpusCount: 98954, translation: 'the girl' },
  { id: 'v-tocmai', rank: 274, word: 'tocmai', corpusCount: 98626, translation: 'just, precisely' },
  { id: 'v-târziu', rank: 275, word: 'târziu', corpusCount: 98476, translation: 'late' },
  { id: 'v-iau', rank: 276, word: 'iau', corpusCount: 97864, translation: 'I take' },
  { id: 'v-partea', rank: 277, word: 'partea', corpusCount: 97743, translation: 'the part, the side' },
  { id: 'v-adică', rank: 278, word: 'adică', corpusCount: 97640, translation: 'I mean, that is' },
  { id: 'v-zile', rank: 279, word: 'zile', corpusCount: 97463, translation: 'days' },
  { id: 'v-cele', rank: 280, word: 'cele', corpusCount: 96951, translation: 'the ones (o-plural)' },
  { id: 'v-seara', rank: 281, word: 'seara', corpusCount: 96921, translation: 'the evening; in the evening' },
  { id: 'v-mereu', rank: 282, word: 'mereu', corpusCount: 96571, translation: 'always' },
  { id: 'v-imediat', rank: 286, word: 'imediat', corpusCount: 95633, translation: 'right away' },
  { id: 'v-azi', rank: 287, word: 'azi', corpusCount: 95113, translation: 'today' },
  { id: 'v-spre', rank: 289, word: 'spre', corpusCount: 94959, translation: 'towards' },
  { id: 'v-împreună', rank: 290, word: 'împreună', corpusCount: 94941, translation: 'together' },
  { id: 'v-plecat', rank: 291, word: 'plecat', corpusCount: 94419, translation: 'left, gone' },
  { id: 'v-trebuia', rank: 292, word: 'trebuia', corpusCount: 93998, translation: 'had to, was supposed to' },
  { id: 'v-terminat', rank: 293, word: 'terminat', corpusCount: 93202, translation: 'finished' },
  { id: 'v-crezut', rank: 294, word: 'crezut', corpusCount: 92746, translation: 'believed' },
  { id: 'v-iubesc', rank: 295, word: 'iubesc', corpusCount: 92107, translation: 'I love' },
  { id: 'v-început', rank: 296, word: 'început', corpusCount: 91780, translation: 'begun; the beginning' },
  { id: 'v-copii', rank: 297, word: 'copii', corpusCount: 91282, translation: 'children' },
  { id: 'v-departe', rank: 299, word: 'departe', corpusCount: 90343, translation: 'far' },
  { id: 'v-măcar', rank: 300, word: 'măcar', corpusCount: 90152, translation: 'at least' },
  { id: 'v-pierdut', rank: 301, word: 'pierdut', corpusCount: 89857, translation: 'lost' },
  { id: 'v-banii', rank: 303, word: 'banii', corpusCount: 89608, translation: 'the money' },
  { id: 'v-sub', rank: 306, word: 'sub', corpusCount: 89225, translation: 'under' },
  { id: 'v-frumos', rank: 307, word: 'frumos', corpusCount: 88726, translation: 'beautiful, nice' },
  { id: 'v-aceste', rank: 308, word: 'aceste', corpusCount: 88383, translation: 'these (formal)' },
  { id: 'v-tată', rank: 310, word: 'tată', corpusCount: 87024, translation: 'father, Dad' },
  { id: 'v-mâine', rank: 311, word: 'mâine', corpusCount: 86973, translation: 'tomorrow' },
  { id: 'v-plec', rank: 312, word: 'plec', corpusCount: 86968, translation: 'I leave' },
  { id: 'v-ăla', rank: 314, word: 'ăla', corpusCount: 86814, translation: 'that one' },
  { id: 'v-mei', rank: 315, word: 'mei', corpusCount: 86529, translation: 'my (un-plural)' },
  { id: 'v-aveți', rank: 316, word: 'aveți', corpusCount: 85764, translation: 'you (all) have' },
  { id: 'v-păi', rank: 317, word: 'păi', corpusCount: 84705, translation: 'well…' },
  { id: 'v-tipul', rank: 318, word: 'tipul', corpusCount: 84573, translation: 'the guy' },
  { id: 'v-înțeleg', rank: 319, word: 'înțeleg', corpusCount: 84056, translation: 'I understand' },
  { id: 'v-greu', rank: 320, word: 'greu', corpusCount: 83708, translation: 'hard; heavy' },
  { id: 'v-minute', rank: 321, word: 'minute', corpusCount: 82842, translation: 'minutes' },
  { id: 'v-dai', rank: 322, word: 'dai', corpusCount: 82829, translation: 'you give' },
  { id: 'v-sus', rank: 323, word: 'sus', corpusCount: 82634, translation: 'up' },
  { id: 'v-drumul', rank: 325, word: 'drumul', corpusCount: 82548, translation: 'the road, the way' },
  { id: 'v-vedea', rank: 327, word: 'vedea', corpusCount: 81991, translation: 'see' },
  { id: 'v-mie', rank: 329, word: 'mie', corpusCount: 81518, translation: '(to) me' },
  { id: 'v-desigur', rank: 330, word: 'desigur', corpusCount: 80179, translation: 'of course' },
  { id: 'v-așteaptă', rank: 332, word: 'așteaptă', corpusCount: 80042, translation: 'wait!' },
  { id: 'v-idee', rank: 337, word: 'idee', corpusCount: 78875, translation: 'idea' },
  { id: 'v-aceea', rank: 339, word: 'aceea', corpusCount: 78021, translation: 'that (formal); (de aceea) that\'s why' },
  { id: 'v-ale', rank: 340, word: 'ale', corpusCount: 77949, translation: 'of — the plural possessive linker' },
  { id: 'v-tip', rank: 341, word: 'tip', corpusCount: 77866, translation: 'guy; type' },
  { id: 'v-ultima', rank: 342, word: 'ultima', corpusCount: 77846, translation: 'the last (o)' },
  { id: 'v-femeie', rank: 343, word: 'femeie', corpusCount: 77833, translation: 'woman' },
  { id: 'v-înțeles', rank: 344, word: 'înțeles', corpusCount: 77740, translation: 'understood' },
  { id: 'v-sper', rank: 345, word: 'sper', corpusCount: 77073, translation: 'I hope' },
  { id: 'v-primul', rank: 347, word: 'primul', corpusCount: 76782, translation: 'the first' },
  { id: 'v-gândit', rank: 348, word: 'gândit', corpusCount: 76715, translation: 'thought' },
  { id: 'v-vreo', rank: 349, word: 'vreo', corpusCount: 76599, translation: 'any; about (with numbers)' },
  { id: 'v-copil', rank: 350, word: 'copil', corpusCount: 76579, translation: 'child' },
  { id: 'v-erau', rank: 352, word: 'erau', corpusCount: 76103, translation: 'they were' },
  { id: 'v-seama', rank: 353, word: 'seama', corpusCount: 76060, translation: '(îmi dau seama) I realise' },
  { id: 'v-tare', rank: 354, word: 'tare', corpusCount: 75939, translation: 'strong, loud; really (colloquial)' },
  { id: 'v-pus', rank: 355, word: 'pus', corpusCount: 75757, translation: 'put' },
  { id: 'v-bune', rank: 356, word: 'bune', corpusCount: 75526, translation: 'good (o-plural)' },
  { id: 'v-merg', rank: 358, word: 'merg', corpusCount: 75372, translation: 'I go' },
  { id: 'v-moment', rank: 359, word: 'moment', corpusCount: 74951, translation: 'moment' },
  { id: 'v-dus', rank: 360, word: 'dus', corpusCount: 74738, translation: 'taken; gone' },
  { id: 'v-noastre', rank: 361, word: 'noastre', corpusCount: 74118, translation: 'our (o-plural)' },
  { id: 'v-își', rank: 362, word: 'își', corpusCount: 73484, translation: 'to himself, to herself' },
  { id: 'v-griji', rank: 364, word: 'griji', corpusCount: 72534, translation: 'worries (nu-ți face griji)' },
  { id: 'v-între', rank: 365, word: 'între', corpusCount: 72501, translation: 'between' },
  { id: 'v-minunat', rank: 366, word: 'minunat', corpusCount: 72199, translation: 'wonderful' },
  { id: 'v-vorbești', rank: 367, word: 'vorbești', corpusCount: 72152, translation: 'you speak' },
  { id: 'v-lua', rank: 368, word: 'lua', corpusCount: 72071, translation: 'take' },
  { id: 'v-cauza', rank: 369, word: 'cauza', corpusCount: 71990, translation: '(din cauza) because of' },
  { id: 'v-pic', rank: 370, word: 'pic', corpusCount: 71810, translation: '(un pic) a bit' },
  { id: 'v-poftim', rank: 371, word: 'poftim', corpusCount: 71671, translation: 'here you are; pardon?' },
  { id: 'v-simți', rank: 372, word: 'simți', corpusCount: 71602, translation: 'you feel' },
  { id: 'v-ajunge', rank: 375, word: 'ajunge', corpusCount: 71396, translation: 'arrives; that\'s enough' },
  { id: 'v-urmă', rank: 376, word: 'urmă', corpusCount: 71379, translation: '(până la urmă) in the end' },
  { id: 'v-ba', rank: 378, word: 'ba', corpusCount: 71256, translation: '(ba da / ba nu) oh yes it is / oh no it isn\'t' },
  { id: 'v-ajutor', rank: 379, word: 'ajutor', corpusCount: 71195, translation: 'help' },
  { id: 'v-vorbim', rank: 380, word: 'vorbim', corpusCount: 70690, translation: 'we speak' },
  { id: 'v-ore', rank: 381, word: 'ore', corpusCount: 70383, translation: 'hours' },
  { id: 'v-noaptea', rank: 382, word: 'noaptea', corpusCount: 70257, translation: 'at night' },
  { id: 'v-corect', rank: 383, word: 'corect', corpusCount: 69342, translation: 'correct; fair' },
  { id: 'v-ciudat', rank: 384, word: 'ciudat', corpusCount: 69057, translation: 'strange' },
  { id: 'v-ele', rank: 385, word: 'ele', corpusCount: 68920, translation: 'they (female)' },
  { id: 'v-problemă', rank: 386, word: 'problemă', corpusCount: 68851, translation: 'problem' },
  { id: 'v-probleme', rank: 389, word: 'probleme', corpusCount: 68496, translation: 'problems' },
  { id: 'v-încercat', rank: 390, word: 'încercat', corpusCount: 68417, translation: 'tried' },
  { id: 'v-pune', rank: 391, word: 'pune', corpusCount: 68380, translation: 'puts; put!' },
  { id: 'v-întotdeauna', rank: 392, word: 'întotdeauna', corpusCount: 68346, translation: 'always' },
  { id: 'v-credeam', rank: 394, word: 'credeam', corpusCount: 67854, translation: 'I thought (I was thinking)' },
  { id: 'v-vorbit', rank: 397, word: 'vorbit', corpusCount: 66761, translation: 'spoken' },
  { id: 'v-adus', rank: 398, word: 'adus', corpusCount: 66760, translation: 'brought' },
  { id: 'v-fiul', rank: 399, word: 'fiul', corpusCount: 66732, translation: 'the son' },
  { id: 'v-vreodată', rank: 400, word: 'vreodată', corpusCount: 66519, translation: 'ever' },
  { id: 'v-cap', rank: 401, word: 'cap', corpusCount: 66229, translation: 'head' },
  { id: 'v-luni', rank: 402, word: 'luni', corpusCount: 65799, translation: 'Monday; months' },
  { id: 'v-băieți', rank: 403, word: 'băieți', corpusCount: 65580, translation: 'boys; guys' },
  { id: 'v-vii', rank: 404, word: 'vii', corpusCount: 65565, translation: 'you come' },
  { id: 'v-crede', rank: 406, word: 'crede', corpusCount: 65410, translation: 'believes, thinks' },
  { id: 'v-familia', rank: 407, word: 'familia', corpusCount: 65303, translation: 'the family' },
  { id: 'v-cer', rank: 408, word: 'cer', corpusCount: 65033, translation: 'sky; I ask for' },
  { id: 'v-puteți', rank: 409, word: 'puteți', corpusCount: 64750, translation: 'you (all) can' },
  { id: 'v-ales', rank: 410, word: 'ales', corpusCount: 64708, translation: 'chosen' },
  { id: 'v-altă', rank: 412, word: 'altă', corpusCount: 63942, translation: 'another (o)' },
  { id: 'v-cale', rank: 413, word: 'cale', corpusCount: 63888, translation: 'way, path' },
  { id: 'v-bucur', rank: 414, word: 'bucur', corpusCount: 63704, translation: '(mă bucur) I\'m glad' },
  { id: 'v-nicio', rank: 416, word: 'nicio', corpusCount: 63456, translation: 'no, not a single (o)' },
  { id: 'v-uitat', rank: 417, word: 'uitat', corpusCount: 63182, translation: 'forgotten' },
  { id: 'v-cunosc', rank: 418, word: 'cunosc', corpusCount: 62962, translation: 'I know (a person or place)' },
  { id: 'v-ascultă', rank: 419, word: 'ascultă', corpusCount: 62898, translation: 'listen!' },
  { id: 'v-mulți', rank: 421, word: 'mulți', corpusCount: 62666, translation: 'many (people)' },
  { id: 'v-joc', rank: 422, word: 'joc', corpusCount: 62384, translation: 'game; I play' },
  { id: 'v-ușor', rank: 423, word: 'ușor', corpusCount: 62126, translation: 'easy; light' },
  { id: 'v-oricum', rank: 424, word: 'oricum', corpusCount: 62103, translation: 'anyway' },
  { id: 'v-iei', rank: 425, word: 'iei', corpusCount: 61950, translation: 'you take' },
  { id: 'v-caz', rank: 426, word: 'caz', corpusCount: 61873, translation: 'case' },
  { id: 'v-mașina', rank: 427, word: 'mașina', corpusCount: 61548, translation: 'the car' },
  { id: 'v-ochii', rank: 428, word: 'ochii', corpusCount: 61492, translation: 'the eyes' },
  { id: 'v-altceva', rank: 429, word: 'altceva', corpusCount: 61397, translation: 'something else' },
  { id: 'v-lume', rank: 431, word: 'lume', corpusCount: 61247, translation: 'world; people' },
  { id: 'v-mergi', rank: 432, word: 'mergi', corpusCount: 61095, translation: 'you go' },
  { id: 'v-patru', rank: 433, word: 'patru', corpusCount: 60848, translation: 'four' },
  { id: 'v-cinci', rank: 434, word: 'cinci', corpusCount: 60587, translation: 'five' },
  { id: 'v-încredere', rank: 435, word: 'încredere', corpusCount: 60541, translation: 'trust' },
  { id: 'v-veni', rank: 436, word: 'veni', corpusCount: 60276, translation: 'come' },
  { id: 'v-salut', rank: 437, word: 'salut', corpusCount: 60116, translation: 'hi' },
  { id: 'v-prins', rank: 439, word: 'prins', corpusCount: 59993, translation: 'caught' },
  { id: 'v-acord', rank: 440, word: 'acord', corpusCount: 59845, translation: '(de acord) agreed' },
  { id: 'v-primit', rank: 443, word: 'primit', corpusCount: 59333, translation: 'received' },
  { id: 'v-telefon', rank: 444, word: 'telefon', corpusCount: 59138, translation: 'phone' },
  { id: 'v-lăsat', rank: 445, word: 'lăsat', corpusCount: 58792, translation: 'left, let' },
  { id: 'v-grozav', rank: 446, word: 'grozav', corpusCount: 58754, translation: 'great' },
  { id: 'v-faceți', rank: 447, word: 'faceți', corpusCount: 58630, translation: 'you (all) do' },
  { id: 'v-știm', rank: 450, word: 'știm', corpusCount: 58091, translation: 'we know' },
  { id: 'v-lângă', rank: 451, word: 'lângă', corpusCount: 57902, translation: 'next to' },
  { id: 'v-fratele', rank: 452, word: 'fratele', corpusCount: 57852, translation: 'the brother' },
  { id: 'v-prieten', rank: 453, word: 'prieten', corpusCount: 57706, translation: 'friend' },
  { id: 'v-important', rank: 454, word: 'important', corpusCount: 57564, translation: 'important' },
  { id: 'v-câte', rank: 455, word: 'câte', corpusCount: 57522, translation: 'how many (o)' },
  { id: 'v-zici', rank: 457, word: 'zici', corpusCount: 57305, translation: 'you say' },
  { id: 'v-omul', rank: 461, word: 'omul', corpusCount: 56701, translation: 'the man, the person' },
  { id: 'v-dragă', rank: 462, word: 'dragă', corpusCount: 55870, translation: 'dear' },
  { id: 'v-pun', rank: 463, word: 'pun', corpusCount: 55741, translation: 'I put' },
  { id: 'v-găsi', rank: 464, word: 'găsi', corpusCount: 55181, translation: 'find' },
  { id: 'v-vorbi', rank: 465, word: 'vorbi', corpusCount: 54752, translation: 'speak' },
  { id: 'v-simplu', rank: 466, word: 'simplu', corpusCount: 54742, translation: 'simple' },
  { id: 'v-sunat', rank: 467, word: 'sunat', corpusCount: 54717, translation: 'called, rung' },
  { id: 'v-doamnă', rank: 468, word: 'doamnă', corpusCount: 54582, translation: 'madam, lady' },
  { id: 'v-odată', rank: 469, word: 'odată', corpusCount: 54552, translation: 'once, at one time' },
  { id: 'v-pasă', rank: 470, word: 'pasă', corpusCount: 54512, translation: '(nu-mi pasă) I don\'t care' },
  { id: 'v-mâna', rank: 471, word: 'mâna', corpusCount: 54349, translation: 'the hand' },
  { id: 'v-pleci', rank: 472, word: 'pleci', corpusCount: 54211, translation: 'you leave' },
  { id: 'v-veți', rank: 473, word: 'veți', corpusCount: 53997, translation: 'you (all) will' },
  { id: 'v-stau', rank: 475, word: 'stau', corpusCount: 53702, translation: 'I stay; I live' },
  { id: 'v-prieteni', rank: 477, word: 'prieteni', corpusCount: 53564, translation: 'friends' },
  { id: 'v-soția', rank: 479, word: 'soția', corpusCount: 53530, translation: 'the wife' },
  { id: 'v-alte', rank: 480, word: 'alte', corpusCount: 53170, translation: 'other (o-plural)' },
  { id: 'v-arată', rank: 481, word: 'arată', corpusCount: 52679, translation: 'shows; looks' },
  { id: 'v-pleacă', rank: 482, word: 'pleacă', corpusCount: 52652, translation: 'leaves' },
  { id: 'v-oraș', rank: 483, word: 'oraș', corpusCount: 52534, translation: 'town, city' },
  { id: 'v-drum', rank: 484, word: 'drum', corpusCount: 52287, translation: 'road, way' },
  { id: 'v-mod', rank: 485, word: 'mod', corpusCount: 52152, translation: 'way, manner' },
  { id: 'v-întors', rank: 486, word: 'întors', corpusCount: 52065, translation: 'returned' },
  { id: 'v-mic', rank: 487, word: 'mic', corpusCount: 52019, translation: 'small' },
  { id: 'v-alo', rank: 489, word: 'alo', corpusCount: 51999, translation: 'hello? (phone)' },
  { id: 'v-treabă', rank: 491, word: 'treabă', corpusCount: 51349, translation: 'job, business' },
  { id: 'v-legătură', rank: 493, word: 'legătură', corpusCount: 51309, translation: 'link, connection' },
  { id: 'v-nouă', rank: 495, word: 'nouă', corpusCount: 51153, translation: 'nine; new (o); to us' },
  { id: 'v-aveam', rank: 496, word: 'aveam', corpusCount: 51111, translation: 'I had, we had' },
  { id: 'v-știți', rank: 497, word: 'știți', corpusCount: 50994, translation: 'you (all) know' },
  { id: 'v-alt', rank: 498, word: 'alt', corpusCount: 50990, translation: 'another' },
  { id: 'v-curând', rank: 499, word: 'curând', corpusCount: 50830, translation: 'soon' },
  { id: 'v-chestia', rank: 500, word: 'chestia', corpusCount: 50694, translation: 'the thing' },
  { id: 'v-capul', rank: 501, word: 'capul', corpusCount: 50558, translation: 'the head' },
  { id: 'v-știam', rank: 502, word: 'știam', corpusCount: 50556, translation: 'I knew' },
  { id: 'v-gând', rank: 503, word: 'gând', corpusCount: 50523, translation: 'thought' },
  { id: 'v-începe', rank: 504, word: 'începe', corpusCount: 50374, translation: 'begins' },
  { id: 'v-spate', rank: 505, word: 'spate', corpusCount: 50259, translation: 'back' },
  { id: 'v-către', rank: 506, word: 'către', corpusCount: 50118, translation: 'towards' },
  { id: 'v-astfel', rank: 507, word: 'astfel', corpusCount: 50091, translation: 'thus, so' },
  { id: 'v-noroc', rank: 508, word: 'noroc', corpusCount: 50088, translation: 'luck; cheers' },
  { id: 'v-trimis', rank: 509, word: 'trimis', corpusCount: 50041, translation: 'sent' },
  { id: 'v-posibil', rank: 510, word: 'posibil', corpusCount: 49940, translation: 'possible' },
  { id: 'v-apă', rank: 511, word: 'apă', corpusCount: 49848, translation: 'water' },
  { id: 'v-singurul', rank: 512, word: 'singurul', corpusCount: 49845, translation: 'the only one' },
  { id: 'v-mersi', rank: 513, word: 'mersi', corpusCount: 49729, translation: 'thanks' },
  { id: 'v-încearcă', rank: 514, word: 'încearcă', corpusCount: 49635, translation: 'try!' },
  { id: 'v-inima', rank: 515, word: 'inima', corpusCount: 49488, translation: 'the heart' },
  { id: 'v-copilul', rank: 516, word: 'copilul', corpusCount: 49338, translation: 'the child' },
  { id: 'v-frumoasă', rank: 517, word: 'frumoasă', corpusCount: 49116, translation: 'beautiful (o)' },
  { id: 'v-las', rank: 518, word: 'las', corpusCount: 49036, translation: 'I leave (it), I let' },
  { id: 'v-bărbat', rank: 519, word: 'bărbat', corpusCount: 48854, translation: 'man' },
  { id: 'v-nume', rank: 521, word: 'nume', corpusCount: 48710, translation: 'name' },
  { id: 'v-adevărul', rank: 522, word: 'adevărul', corpusCount: 48642, translation: 'the truth' },
  { id: 'v-tăi', rank: 525, word: 'tăi', corpusCount: 48385, translation: 'your (un-plural)' },
  { id: 'v-rămâne', rank: 526, word: 'rămâne', corpusCount: 48381, translation: 'stays, remains' },
  { id: 'v-ieși', rank: 527, word: 'ieși', corpusCount: 48380, translation: 'you go out; go out!' },
  { id: 'v-prietenul', rank: 528, word: 'prietenul', corpusCount: 48362, translation: 'the friend; boyfriend' },
  { id: 'v-auzi', rank: 529, word: 'auzi', corpusCount: 48321, translation: 'you hear' },
  { id: 'v-domnul', rank: 530, word: 'domnul', corpusCount: 48313, translation: 'the gentleman, Mr' },
  { id: 'v-niciun', rank: 531, word: 'niciun', corpusCount: 48241, translation: 'no, not a single' },
  { id: 'v-încerc', rank: 533, word: 'încerc', corpusCount: 48190, translation: 'I try' },
  { id: 'v-întoarce', rank: 534, word: 'întoarce', corpusCount: 48063, translation: 'returns; turns' },
  { id: 'v-vreme', rank: 535, word: 'vreme', corpusCount: 47863, translation: 'weather; time' },
  { id: 'v-pleca', rank: 536, word: 'pleca', corpusCount: 47824, translation: 'leave' },
  { id: 'v-înțelegi', rank: 537, word: 'înțelegi', corpusCount: 47636, translation: 'you understand' },
  { id: 'v-lăsa', rank: 538, word: 'lăsa', corpusCount: 47585, translation: 'leave, let' },
  { id: 'v-spatele', rank: 539, word: 'spatele', corpusCount: 47579, translation: 'the back' },
  { id: 'v-împotriva', rank: 540, word: 'împotriva', corpusCount: 47349, translation: 'against' },
  { id: 'v-frate', rank: 541, word: 'frate', corpusCount: 47312, translation: 'brother' },
  { id: 'v-contează', rank: 542, word: 'contează', corpusCount: 47274, translation: 'matters' },
  { id: 'v-ajut', rank: 543, word: 'ajut', corpusCount: 47224, translation: 'I help' },
  { id: 'v-copiii', rank: 544, word: 'copiii', corpusCount: 47209, translation: 'the children' },
  { id: 'v-pace', rank: 545, word: 'pace', corpusCount: 47184, translation: 'peace' },
  { id: 'v-familie', rank: 546, word: 'familie', corpusCount: 47160, translation: 'family' },
  { id: 'v-pui', rank: 549, word: 'pui', corpusCount: 47015, translation: 'chick; chicken; you put' },
  { id: 'v-an', rank: 550, word: 'an', corpusCount: 46679, translation: 'year' },
  { id: 'v-minte', rank: 552, word: 'minte', corpusCount: 46576, translation: 'mind; lies' },
  { id: 'v-deloc', rank: 553, word: 'deloc', corpusCount: 46382, translation: 'at all' },
  { id: 'v-parcă', rank: 554, word: 'parcă', corpusCount: 46361, translation: 'as if, it seems' },
  { id: 'v-același', rank: 555, word: 'același', corpusCount: 46280, translation: 'the same' },
  { id: 'v-perfect', rank: 556, word: 'perfect', corpusCount: 46254, translation: 'perfect(ly)' },
  { id: 'v-mers', rank: 557, word: 'mers', corpusCount: 46005, translation: 'gone, walked' },
  { id: 'v-astăzi', rank: 558, word: 'astăzi', corpusCount: 45819, translation: 'today' },
  { id: 'v-mari', rank: 559, word: 'mari', corpusCount: 45725, translation: 'big (plural)' },
  { id: 'v-plecăm', rank: 562, word: 'plecăm', corpusCount: 45544, translation: 'we leave' },
  { id: 'v-erai', rank: 563, word: 'erai', corpusCount: 45505, translation: 'you were' },
  { id: 'v-dimineața', rank: 564, word: 'dimineața', corpusCount: 45472, translation: 'in the morning' },
  { id: 'v-oră', rank: 565, word: 'oră', corpusCount: 45462, translation: 'hour' },
  { id: 'v-plac', rank: 566, word: 'plac', corpusCount: 45373, translation: '(îmi plac) I like (them)' },
  { id: 'v-motiv', rank: 568, word: 'motiv', corpusCount: 45257, translation: 'reason' },
  { id: 'v-fă', rank: 569, word: 'fă', corpusCount: 44919, translation: 'do!' },
  { id: 'v-întreb', rank: 570, word: 'întreb', corpusCount: 44804, translation: 'I ask' },
  { id: 'v-fiica', rank: 571, word: 'fiica', corpusCount: 44619, translation: 'the daughter' },
  { id: 'v-devreme', rank: 572, word: 'devreme', corpusCount: 44226, translation: 'early' },
  { id: 'v-sigură', rank: 574, word: 'sigură', corpusCount: 44070, translation: 'sure (o)' },
  { id: 'v-amândoi', rank: 575, word: 'amândoi', corpusCount: 43920, translation: 'both' },
  { id: 'v-gândesc', rank: 576, word: 'gândesc', corpusCount: 43710, translation: '(mă gândesc) I\'m thinking' },
  { id: 'v-persoană', rank: 579, word: 'persoană', corpusCount: 43428, translation: 'person' },
  { id: 'v-rămas', rank: 580, word: 'rămas', corpusCount: 43422, translation: 'stayed; left over' },
  { id: 'v-vreți', rank: 581, word: 'vreți', corpusCount: 43409, translation: 'you (all) want' },
  { id: 'v-aduc', rank: 582, word: 'aduc', corpusCount: 43292, translation: 'I bring' },
  { id: 'v-mâinile', rank: 583, word: 'mâinile', corpusCount: 43274, translation: 'the hands' },
  { id: 'v-fiindcă', rank: 585, word: 'fiindcă', corpusCount: 42956, translation: 'because' },
  { id: 'v-fericit', rank: 586, word: 'fericit', corpusCount: 42926, translation: 'happy' },
  { id: 'v-revedere', rank: 587, word: 'revedere', corpusCount: 42895, translation: '(la revedere) goodbye' },
  { id: 'v-amintesc', rank: 588, word: 'amintesc', corpusCount: 42807, translation: '(îmi amintesc) I remember' },
  { id: 'v-mică', rank: 589, word: 'mică', corpusCount: 42762, translation: 'small (o)' },
  { id: 'v-sora', rank: 591, word: 'sora', corpusCount: 42628, translation: 'the sister' },
  { id: 'v-intrat', rank: 592, word: 'intrat', corpusCount: 42600, translation: 'entered' },
  { id: 'v-jumătate', rank: 593, word: 'jumătate', corpusCount: 42532, translation: 'half' },
  { id: 'v-sună', rank: 594, word: 'sună', corpusCount: 42481, translation: 'rings; call!' },
  { id: 'v-prost', rank: 595, word: 'prost', corpusCount: 42452, translation: 'stupid; badly' },
  { id: 'v-sun', rank: 596, word: 'sun', corpusCount: 42185, translation: 'I call' },
  { id: 'v-nebun', rank: 597, word: 'nebun', corpusCount: 42163, translation: 'mad, crazy' },
  { id: 'v-zic', rank: 598, word: 'zic', corpusCount: 42131, translation: 'I say' },
  { id: 'v-drăguț', rank: 599, word: 'drăguț', corpusCount: 42111, translation: 'nice, sweet' },
  { id: 'v-numărul', rank: 600, word: 'numărul', corpusCount: 41976, translation: 'the number' },
  { id: 'v-vină', rank: 602, word: 'vină', corpusCount: 41884, translation: 'fault; (să vină) come' },
  { id: 'v-aud', rank: 604, word: 'aud', corpusCount: 41662, translation: 'I hear' },
  { id: 'v-cumva', rank: 605, word: 'cumva', corpusCount: 41629, translation: 'somehow' },
  { id: 'v-muncă', rank: 607, word: 'muncă', corpusCount: 41383, translation: 'work' },
  { id: 'v-cunoscut', rank: 609, word: 'cunoscut', corpusCount: 41231, translation: 'known; met' },
  { id: 'v-faptul', rank: 610, word: 'faptul', corpusCount: 41230, translation: 'the fact' },
  { id: 'v-restul', rank: 611, word: 'restul', corpusCount: 41072, translation: 'the rest; the change' },
  { id: 'v-undeva', rank: 612, word: 'undeva', corpusCount: 41042, translation: 'somewhere' },
  { id: 'v-pa', rank: 616, word: 'pa', corpusCount: 40771, translation: 'bye' },
  { id: 'v-găsesc', rank: 618, word: 'găsesc', corpusCount: 40519, translation: 'I find' },
  { id: 'v-vreun', rank: 619, word: 'vreun', corpusCount: 40402, translation: 'any' },
  { id: 'v-aflat', rank: 622, word: 'aflat', corpusCount: 40068, translation: 'found out' },
  { id: 'v-drept', rank: 624, word: 'drept', corpusCount: 39943, translation: 'right; straight' },
  { id: 'v-știut', rank: 626, word: 'știut', corpusCount: 39884, translation: 'known' },
  { id: 'v-aduce', rank: 630, word: 'aduce', corpusCount: 39471, translation: 'brings' },
  { id: 'v-ușa', rank: 631, word: 'ușa', corpusCount: 39343, translation: 'the door' },
  { id: 'v-dimineață', rank: 632, word: 'dimineață', corpusCount: 39238, translation: 'morning' },
  { id: 'v-jur', rank: 633, word: 'jur', corpusCount: 39182, translation: 'I swear; (în jur) around' },
  { id: 'v-reușit', rank: 634, word: 'reușit', corpusCount: 39176, translation: 'managed, succeeded' },
  { id: 'v-momentul', rank: 635, word: 'momentul', corpusCount: 39172, translation: 'the moment' },
  { id: 'v-luăm', rank: 636, word: 'luăm', corpusCount: 39160, translation: 'we take' },
  { id: 'v-vrem', rank: 638, word: 'vrem', corpusCount: 39141, translation: 'we want' },
  { id: 'v-cerut', rank: 639, word: 'cerut', corpusCount: 39112, translation: 'asked for' },
  { id: 'v-ultimul', rank: 640, word: 'ultimul', corpusCount: 38881, translation: 'the last' },
  { id: 'v-ți', rank: 641, word: 'ți', corpusCount: 38684, translation: '(to) you — short form (ți-am zis)' },
  { id: 'v-vadă', rank: 643, word: 'vadă', corpusCount: 38404, translation: '(să vadă) see' },
  { id: 'v-greșit', rank: 644, word: 'greșit', corpusCount: 38373, translation: 'wrong' },
  { id: 'v-abia', rank: 645, word: 'abia', corpusCount: 38232, translation: 'barely; only just' },
  { id: 'v-dă', rank: 646, word: 'dă', corpusCount: 38092, translation: 'gives; give!' },
  { id: 'v-genul', rank: 647, word: 'genul', corpusCount: 37880, translation: 'the kind, the type' },
  { id: 'v-altfel', rank: 648, word: 'altfel', corpusCount: 37781, translation: 'otherwise; differently' },
  { id: 'v-foc', rank: 650, word: 'foc', corpusCount: 37589, translation: 'fire' },
  { id: 'v-întâi', rank: 651, word: 'întâi', corpusCount: 37509, translation: 'first' },
  { id: 'v-înăuntru', rank: 652, word: 'înăuntru', corpusCount: 37470, translation: 'inside' },
  { id: 'v-totuși', rank: 654, word: 'totuși', corpusCount: 37404, translation: 'still, however' },
  { id: 'v-trece', rank: 658, word: 'trece', corpusCount: 37159, translation: 'passes' },
  { id: 'v-vorbește', rank: 660, word: 'vorbește', corpusCount: 36914, translation: 'speaks' },
  { id: 'v-scris', rank: 661, word: 'scris', corpusCount: 36895, translation: 'written' },
  { id: 'v-schimbat', rank: 662, word: 'schimbat', corpusCount: 36880, translation: 'changed' },
  { id: 'v-uneori', rank: 663, word: 'uneori', corpusCount: 36861, translation: 'sometimes' },
  { id: 'v-soțul', rank: 664, word: 'soțul', corpusCount: 36702, translation: 'the husband' },
  { id: 'v-deschide', rank: 665, word: 'deschide', corpusCount: 36560, translation: 'opens; open!' },
  { id: 'v-dea', rank: 666, word: 'dea', corpusCount: 36510, translation: '(să dea) give' },
  { id: 'v-altcineva', rank: 667, word: 'altcineva', corpusCount: 36459, translation: 'someone else' },
  { id: 'v-prietenii', rank: 669, word: 'prietenii', corpusCount: 36341, translation: 'the friends' },
  { id: 'v-pământ', rank: 672, word: 'pământ', corpusCount: 36245, translation: 'earth, ground' },
  { id: 'v-șansă', rank: 673, word: 'șansă', corpusCount: 36185, translation: 'chance' },
  { id: 'v-voiam', rank: 675, word: 'voiam', corpusCount: 36166, translation: 'I wanted' },
  { id: 'v-arăți', rank: 676, word: 'arăți', corpusCount: 36092, translation: 'you look' },
  { id: 'v-școală', rank: 678, word: 'școală', corpusCount: 36005, translation: 'school' },
  { id: 'v-ieri', rank: 679, word: 'ieri', corpusCount: 35966, translation: 'yesterday' },
  { id: 'v-normal', rank: 680, word: 'normal', corpusCount: 35955, translation: 'normal; of course' },
  { id: 'v-sfârșit', rank: 681, word: 'sfârșit', corpusCount: 35932, translation: 'end' },
  { id: 'v-cameră', rank: 682, word: 'cameră', corpusCount: 35815, translation: 'room' },
  { id: 'v-devenit', rank: 683, word: 'devenit', corpusCount: 35811, translation: 'become' },
  { id: 'v-clar', rank: 684, word: 'clar', corpusCount: 35772, translation: 'clear' },
  { id: 'v-femei', rank: 685, word: 'femei', corpusCount: 35755, translation: 'women' },
  { id: 'v-unele', rank: 687, word: 'unele', corpusCount: 35407, translation: 'some (o)' },
  { id: 'v-tuturor', rank: 688, word: 'tuturor', corpusCount: 35347, translation: 'to everyone' },
  { id: 'v-lasă', rank: 689, word: 'lasă', corpusCount: 35340, translation: 'leave it; let!' },
  { id: 'v-zice', rank: 691, word: 'zice', corpusCount: 35222, translation: 'says' },
  { id: 'v-săptămâni', rank: 692, word: 'săptămâni', corpusCount: 35143, translation: 'weeks' },
  { id: 'v-aibă', rank: 693, word: 'aibă', corpusCount: 35109, translation: '(să aibă) have' },
  { id: 'v-uit', rank: 694, word: 'uit', corpusCount: 35106, translation: 'I forget' },
  { id: 'v-șase', rank: 695, word: 'șase', corpusCount: 35051, translation: 'six' },
  { id: 'v-amuzant', rank: 699, word: 'amuzant', corpusCount: 34924, translation: 'funny' },
  { id: 'v-intră', rank: 701, word: 'intră', corpusCount: 34785, translation: 'enters; come in!' },
  { id: 'v-liber', rank: 702, word: 'liber', corpusCount: 34767, translation: 'free' },
  { id: 'v-ideea', rank: 703, word: 'ideea', corpusCount: 34726, translation: 'the idea' },
  { id: 'v-multă', rank: 704, word: 'multă', corpusCount: 34723, translation: 'much, a lot of (o)' },
  { id: 'v-frică', rank: 705, word: 'frică', corpusCount: 34693, translation: 'fear' },
  { id: 'v-alea', rank: 706, word: 'alea', corpusCount: 34649, translation: 'those (o)' },
  { id: 'v-ci', rank: 707, word: 'ci', corpusCount: 34604, translation: 'but (rather)' },
  { id: 'v-găsim', rank: 708, word: 'găsim', corpusCount: 34468, translation: 'we find' },
  { id: 'v-folosit', rank: 709, word: 'folosit', corpusCount: 34463, translation: 'used' },
  { id: 'v-ieșit', rank: 710, word: 'ieșit', corpusCount: 34385, translation: 'gone out' },
  { id: 'v-pat', rank: 711, word: 'pat', corpusCount: 34303, translation: 'bed' },
  { id: 'v-băiat', rank: 712, word: 'băiat', corpusCount: 34275, translation: 'boy' },
  { id: 'v-trecută', rank: 714, word: 'trecută', corpusCount: 33978, translation: 'last, past (o): săptămâna trecută' },
  { id: 'v-doctor', rank: 716, word: 'doctor', corpusCount: 33892, translation: 'doctor' },
  { id: 'v-petrecere', rank: 721, word: 'petrecere', corpusCount: 33751, translation: 'party' },
  { id: 'v-plus', rank: 722, word: 'plus', corpusCount: 33712, translation: 'plus, also' },
  { id: 'v-pur', rank: 725, word: 'pur', corpusCount: 33562, translation: 'pure; (pur și simplu) simply' },
  { id: 'v-spital', rank: 726, word: 'spital', corpusCount: 33489, translation: 'hospital' },
  { id: 'v-întâlnit', rank: 727, word: 'întâlnit', corpusCount: 33421, translation: 'met' },
  { id: 'v-încât', rank: 730, word: 'încât', corpusCount: 33218, translation: '(așa încât) so that' },
  { id: 'v-felul', rank: 731, word: 'felul', corpusCount: 33153, translation: 'the way, the kind' },
  { id: 'v-haideți', rank: 732, word: 'haideți', corpusCount: 33134, translation: 'come on (to several people)' },
  { id: 'v-cheamă', rank: 733, word: 'cheamă', corpusCount: 33086, translation: 'calls; (cum te cheamă?) what\'s your name?' },
  { id: 'v-direct', rank: 734, word: 'direct', corpusCount: 33084, translation: 'straight, directly' },
  { id: 'v-plăcere', rank: 735, word: 'plăcere', corpusCount: 33083, translation: 'pleasure (cu plăcere)' },
  { id: 'v-sale', rank: 737, word: 'sale', corpusCount: 33049, translation: 'his / her (plural things, formal)' },
  { id: 'v-plăcut', rank: 738, word: 'plăcut', corpusCount: 32993, translation: 'pleasant' },
  { id: 'v-ochi', rank: 739, word: 'ochi', corpusCount: 32932, translation: 'eye, eyes' },
  { id: 'v-spună', rank: 741, word: 'spună', corpusCount: 32823, translation: '(să spună) say' },
  { id: 'v-lași', rank: 742, word: 'lași', corpusCount: 32752, translation: 'you leave, you let' },
  { id: 'v-special', rank: 743, word: 'special', corpusCount: 32561, translation: 'special' },
  { id: 'v-întâlnire', rank: 744, word: 'întâlnire', corpusCount: 32489, translation: 'meeting; date' },
  { id: 'v-trage', rank: 747, word: 'trage', corpusCount: 32382, translation: 'pulls; pull!' },
  { id: 'v-aștept', rank: 748, word: 'aștept', corpusCount: 32275, translation: 'I wait, I\'m waiting' },
  { id: 'v-oricine', rank: 749, word: 'oricine', corpusCount: 32263, translation: 'anyone' },
  { id: 'v-voastră', rank: 750, word: 'voastră', corpusCount: 32123, translation: 'your (you all, o)' },
  { id: 'v-suficient', rank: 753, word: 'suficient', corpusCount: 31969, translation: 'enough' },
  { id: 'v-încerca', rank: 755, word: 'încerca', corpusCount: 31928, translation: 'try' },
  { id: 'v-obicei', rank: 756, word: 'obicei', corpusCount: 31870, translation: 'habit (de obicei — usually)' },
  { id: 'v-complet', rank: 758, word: 'complet', corpusCount: 31814, translation: 'completely' },
  { id: 'v-scrie', rank: 759, word: 'scrie', corpusCount: 31766, translation: 'writes; write!' },
  { id: 'v-însă', rank: 761, word: 'însă', corpusCount: 31715, translation: 'however, but' },
  { id: 'v-dragoste', rank: 762, word: 'dragoste', corpusCount: 31687, translation: 'love' },
  { id: 'v-unu', rank: 763, word: 'unu', corpusCount: 31670, translation: 'one (counting)' },
  { id: 'v-ție', rank: 764, word: 'ție', corpusCount: 31652, translation: 'to you (emphatic)' },
  { id: 'v-unii', rank: 765, word: 'unii', corpusCount: 31595, translation: 'some (people)' },
  { id: 'v-povestea', rank: 767, word: 'povestea', corpusCount: 31498, translation: 'the story' },
  { id: 'v-viitoare', rank: 769, word: 'viitoare', corpusCount: 31444, translation: 'next (o): săptămâna viitoare' },
  { id: 'v-amintești', rank: 770, word: 'amintești', corpusCount: 31432, translation: '(îți amintești?) do you remember?' },
  { id: 'v-telefonul', rank: 771, word: 'telefonul', corpusCount: 31397, translation: 'the phone' },
  { id: 'v-zece', rank: 773, word: 'zece', corpusCount: 31059, translation: 'ten' },
  { id: 'v-sincer', rank: 774, word: 'sincer', corpusCount: 31018, translation: 'honestly' },
  { id: 'v-jurul', rank: 778, word: 'jurul', corpusCount: 30835, translation: '(în jurul) around' },
  { id: 'v-dumneavoastră', rank: 779, word: 'dumneavoastră', corpusCount: 30661, translation: 'you (polite)' },
  { id: 'v-anul', rank: 781, word: 'anul', corpusCount: 30506, translation: 'the year' },
  { id: 'v-ajung', rank: 783, word: 'ajung', corpusCount: 30400, translation: 'I arrive, I get there' },
  { id: 'v-opri', rank: 784, word: 'opri', corpusCount: 30388, translation: 'stop' },
  { id: 'v-minut', rank: 785, word: 'minut', corpusCount: 30385, translation: 'minute' },
  { id: 'v-bineînțeles', rank: 788, word: 'bineînțeles', corpusCount: 30254, translation: 'of course' },
  { id: 'v-vechi', rank: 789, word: 'vechi', corpusCount: 30235, translation: 'old' },
  { id: 'v-aer', rank: 790, word: 'aer', corpusCount: 30153, translation: 'air' },
  { id: 'v-mâncare', rank: 791, word: 'mâncare', corpusCount: 30131, translation: 'food' },
  { id: 'v-treci', rank: 792, word: 'treci', corpusCount: 30103, translation: 'you pass; come over!' },
  { id: 'v-deoarece', rank: 794, word: 'deoarece', corpusCount: 29890, translation: 'because (formal)' },
  { id: 'v-întrebare', rank: 797, word: 'întrebare', corpusCount: 29724, translation: 'question' },
  { id: 'v-picioare', rank: 798, word: 'picioare', corpusCount: 29711, translation: 'legs, feet' },
  { id: 'v-cafea', rank: 799, word: 'cafea', corpusCount: 29677, translation: 'coffee' },
  { id: 'v-schimb', rank: 800, word: 'schimb', corpusCount: 29658, translation: 'exchange (în schimb — instead)' },
  { id: 'v-anume', rank: 803, word: 'anume', corpusCount: 29535, translation: 'namely, particular' },
  { id: 'v-rămâi', rank: 805, word: 'rămâi', corpusCount: 29400, translation: 'you stay; stay!' },
  { id: 'v-lucrez', rank: 808, word: 'lucrez', corpusCount: 29202, translation: 'I work' },
  { id: 'v-promit', rank: 809, word: 'promit', corpusCount: 29196, translation: 'I promise' },
  { id: 'v-ceilalți', rank: 810, word: 'ceilalți', corpusCount: 29104, translation: 'the others' },
  { id: 'v-puternic', rank: 811, word: 'puternic', corpusCount: 29036, translation: 'strong' },
  { id: 'v-părinții', rank: 814, word: 'părinții', corpusCount: 28860, translation: 'the parents' },
  { id: 'v-film', rank: 817, word: 'film', corpusCount: 28710, translation: 'film' },
  { id: 'v-poveste', rank: 818, word: 'poveste', corpusCount: 28659, translation: 'story' },
  { id: 'v-caut', rank: 819, word: 'caut', corpusCount: 28579, translation: 'I\'m looking for' },
  { id: 'v-aceeași', rank: 822, word: 'aceeași', corpusCount: 28530, translation: 'the same (o)' },
  { id: 'v-mor', rank: 823, word: 'mor', corpusCount: 28442, translation: 'I die; (mor după) I\'m crazy about' },
  { id: 'v-cunoști', rank: 824, word: 'cunoști', corpusCount: 28434, translation: 'you know (a person)' },
  { id: 'v-mamei', rank: 825, word: 'mamei', corpusCount: 28353, translation: 'Mum\'s; to Mum' },
  { id: 'v-mână', rank: 826, word: 'mână', corpusCount: 28289, translation: 'hand' },
  { id: 'v-seară', rank: 827, word: 'seară', corpusCount: 28289, translation: 'evening' },
  { id: 'v-super', rank: 828, word: 'super', corpusCount: 28284, translation: 'great' },
  { id: 'v-voie', rank: 832, word: 'voie', corpusCount: 28043, translation: 'permission (ai voie — you\'re allowed)' },
  { id: 'v-învățat', rank: 833, word: 'învățat', corpusCount: 28042, translation: 'learned; taught' },
  { id: 'v-gândești', rank: 836, word: 'gândești', corpusCount: 27973, translation: '(te gândești) you\'re thinking' },
  { id: 'v-întrebat', rank: 837, word: 'întrebat', corpusCount: 27939, translation: 'asked' },
  { id: 'v-întrebări', rank: 838, word: 'întrebări', corpusCount: 27802, translation: 'questions' },
  { id: 'v-fete', rank: 841, word: 'fete', corpusCount: 27676, translation: 'girls' },
  { id: 'v-plece', rank: 842, word: 'plece', corpusCount: 27665, translation: '(să plece) leave' },
  { id: 'v-săptămână', rank: 843, word: 'săptămână', corpusCount: 27593, translation: 'week' },
  { id: 'v-uiți', rank: 845, word: 'uiți', corpusCount: 27499, translation: 'you forget' },
  { id: 'v-femeia', rank: 846, word: 'femeia', corpusCount: 27419, translation: 'the woman' },
  { id: 'v-stați', rank: 849, word: 'stați', corpusCount: 27351, translation: 'stay! wait! (to several people)' },
  { id: 'v-birou', rank: 850, word: 'birou', corpusCount: 27316, translation: 'office; desk' },
  { id: 'v-pregătit', rank: 854, word: 'pregătit', corpusCount: 27158, translation: 'ready, prepared' },
  { id: 'v-lucrat', rank: 855, word: 'lucrat', corpusCount: 27158, translation: 'worked' },
  { id: 'v-mesaj', rank: 864, word: 'mesaj', corpusCount: 26727, translation: 'message' },
  { id: 'v-absolut', rank: 865, word: 'absolut', corpusCount: 26532, translation: 'absolutely' },
  { id: 'v-persoane', rank: 866, word: 'persoane', corpusCount: 26529, translation: 'people' },
  { id: 'v-simțit', rank: 869, word: 'simțit', corpusCount: 26388, translation: 'felt' },
  { id: 'v-accident', rank: 871, word: 'accident', corpusCount: 26313, translation: 'accident' },
  { id: 'v-dor', rank: 873, word: 'dor', corpusCount: 26204, translation: 'longing (mi-e dor — I miss)' },
  { id: 'v-cauți', rank: 874, word: 'cauți', corpusCount: 26195, translation: 'you\'re looking for' },
  { id: 'v-pierde', rank: 879, word: 'pierde', corpusCount: 25972, translation: 'loses' },
  { id: 'v-evident', rank: 880, word: 'evident', corpusCount: 25968, translation: 'obviously' },
  { id: 'v-simte', rank: 881, word: 'simte', corpusCount: 25957, translation: 'feels' },
  { id: 'v-spunem', rank: 882, word: 'spunem', corpusCount: 25945, translation: 'we say' },
  { id: 'v-stă', rank: 883, word: 'stă', corpusCount: 25942, translation: 'stays, sits' },
  { id: 'v-meargă', rank: 887, word: 'meargă', corpusCount: 25860, translation: '(să meargă) go' },
  { id: 'v-urăsc', rank: 888, word: 'urăsc', corpusCount: 25859, translation: 'I hate' },
  { id: 'v-mici', rank: 889, word: 'mici', corpusCount: 25702, translation: 'small (plural); grilled sausages' },
  { id: 'v-caută', rank: 891, word: 'caută', corpusCount: 25596, translation: 'looks for' },
  { id: 'v-plan', rank: 895, word: 'plan', corpusCount: 25488, translation: 'plan' },
  { id: 'v-noștri', rank: 896, word: 'noștri', corpusCount: 25434, translation: 'our (plural)' },
  { id: 'v-folosi', rank: 897, word: 'folosi', corpusCount: 25418, translation: 'use' },
  { id: 'v-citit', rank: 903, word: 'citit', corpusCount: 25228, translation: 'read' },
  { id: 'v-trimite', rank: 904, word: 'trimite', corpusCount: 25214, translation: 'sends; send!' },
  { id: 'v-speriat', rank: 905, word: 'speriat', corpusCount: 25196, translation: 'scared' },
  { id: 'v-foame', rank: 907, word: 'foame', corpusCount: 25146, translation: 'hunger (mi-e foame)' },
  { id: 'v-băiatul', rank: 908, word: 'băiatul', corpusCount: 25107, translation: 'the boy' },
  { id: 'v-clipă', rank: 909, word: 'clipă', corpusCount: 25098, translation: 'moment, blink' },
  { id: 'v-rând', rank: 910, word: 'rând', corpusCount: 25066, translation: 'turn; row (e rândul tău)' },
  { id: 'v-închis', rank: 913, word: 'închis', corpusCount: 24896, translation: 'closed' },
  { id: 'v-carte', rank: 917, word: 'carte', corpusCount: 24678, translation: 'book' },
  { id: 'v-vostru', rank: 918, word: 'vostru', corpusCount: 24646, translation: 'your (you all)' },
  { id: 'v-află', rank: 919, word: 'află', corpusCount: 24611, translation: 'finds out' },
  { id: 'v-atent', rank: 925, word: 'atent', corpusCount: 24510, translation: 'careful, attentive' },
  { id: 'v-termină', rank: 927, word: 'termină', corpusCount: 24464, translation: 'finishes; finish!' },
  { id: 'v-cartea', rank: 928, word: 'cartea', corpusCount: 24450, translation: 'the book' },
  { id: 'v-lucrează', rank: 929, word: 'lucrează', corpusCount: 24442, translation: 'works' },
  { id: 'v-aduci', rank: 931, word: 'aduci', corpusCount: 24393, translation: 'you bring' },
  { id: 'v-masă', rank: 933, word: 'masă', corpusCount: 24374, translation: 'table; meal' },
  { id: 'v-veniți', rank: 934, word: 'veniți', corpusCount: 24334, translation: 'you (all) come; come!' },
  { id: 'v-aminte', rank: 935, word: 'aminte', corpusCount: 24277, translation: '(aduc aminte) remind' },
  { id: 'v-șeful', rank: 936, word: 'șeful', corpusCount: 24264, translation: 'the boss' },
  { id: 'v-echipă', rank: 938, word: 'echipă', corpusCount: 24199, translation: 'team' },
  { id: 'v-baie', rank: 939, word: 'baie', corpusCount: 24158, translation: 'bath; bathroom' },
  { id: 'v-cere', rank: 942, word: 'cere', corpusCount: 24009, translation: 'asks for' },
  { id: 'v-rapid', rank: 946, word: 'rapid', corpusCount: 23805, translation: 'fast' },
  { id: 'v-oară', rank: 947, word: 'oară', corpusCount: 23791, translation: 'time (a doua oară)' },
  { id: 'v-ocup', rank: 950, word: 'ocup', corpusCount: 23720, translation: '(mă ocup de) I deal with' },
  { id: 'v-rost', rank: 951, word: 'rost', corpusCount: 23692, translation: '(a face rost de) get hold of' },
  { id: 'v-orașul', rank: 952, word: 'orașul', corpusCount: 23681, translation: 'the town' },
  { id: 'v-gură', rank: 953, word: 'gură', corpusCount: 23657, translation: 'mouth' },
  { id: 'v-bea', rank: 957, word: 'bea', corpusCount: 23531, translation: 'drinks; drink!' },
  { id: 'v-teamă', rank: 960, word: 'teamă', corpusCount: 23490, translation: 'fear (mi-e teamă)' },
  { id: 'v-ocupat', rank: 962, word: 'ocupat', corpusCount: 23463, translation: 'busy' },
  { id: 'v-alături', rank: 964, word: 'alături', corpusCount: 23421, translation: 'beside, alongside' },
  { id: 'v-greșeală', rank: 965, word: 'greșeală', corpusCount: 23419, translation: 'mistake' },
  { id: 'v-stea', rank: 968, word: 'stea', corpusCount: 23296, translation: 'star' },
  { id: 'v-ies', rank: 969, word: 'ies', corpusCount: 23271, translation: 'I go out' },
  { id: 'v-deschis', rank: 971, word: 'deschis', corpusCount: 23192, translation: 'open' },
  { id: 'v-dormi', rank: 978, word: 'dormi', corpusCount: 23033, translation: 'you sleep; sleep!' },
  { id: 'v-secunde', rank: 979, word: 'secunde', corpusCount: 23019, translation: 'seconds' },
  { id: 'v-bravo', rank: 980, word: 'bravo', corpusCount: 23009, translation: 'well done' },
  { id: 'v-răspunde', rank: 984, word: 'răspunde', corpusCount: 22952, translation: 'answers; answer!' },
  { id: 'v-luați', rank: 988, word: 'luați', corpusCount: 22798, translation: 'take! (to several people)' },
  { id: 'v-crăciun', rank: 991, word: 'Crăciun', corpusCount: 22731, translation: 'Christmas' },
  { id: 'v-petrece', rank: 992, word: 'petrece', corpusCount: 22726, translation: 'spends (time); celebrates' },
  { id: 'v-uită', rank: 993, word: 'uită', corpusCount: 22726, translation: 'look!; forgets' },
  { id: 'v-cuvânt', rank: 994, word: 'cuvânt', corpusCount: 22709, translation: 'word' },
  { id: 'v-răspuns', rank: 995, word: 'răspuns', corpusCount: 22699, translation: 'answer' },
  { id: 'v-interesant', rank: 996, word: 'interesant', corpusCount: 22696, translation: 'interesting' },
  { id: 'v-plin', rank: 997, word: 'plin', corpusCount: 22647, translation: 'full' },
  { id: 'v-cealaltă', rank: 999, word: 'cealaltă', corpusCount: 22568, translation: 'the other one (o)' },
  { id: 'v-primi', rank: 1000, word: 'primi', corpusCount: 22512, translation: 'receive' },
  { id: 'v-tati', rank: 1002, word: 'tati', corpusCount: 22466, translation: 'Daddy' },
  { id: 'v-încep', rank: 1005, word: 'încep', corpusCount: 22396, translation: 'I start' },
  { id: 'v-iubit', rank: 1007, word: 'iubit', corpusCount: 22378, translation: 'loved; boyfriend' },
  { id: 'v-spunea', rank: 1011, word: 'spunea', corpusCount: 22220, translation: 'was saying' },
  { id: 'v-fericită', rank: 1012, word: 'fericită', corpusCount: 22220, translation: 'happy (o)' },
  { id: 'v-lună', rank: 1013, word: 'lună', corpusCount: 22186, translation: 'month; moon' },
  { id: 'v-chestii', rank: 1014, word: 'chestii', corpusCount: 22141, translation: 'stuff, things' },
  { id: 'v-altul', rank: 1018, word: 'altul', corpusCount: 22070, translation: 'another one' },
  { id: 'v-celălalt', rank: 1019, word: 'celălalt', corpusCount: 22049, translation: 'the other one' },
  { id: 'v-căzut', rank: 1026, word: 'căzut', corpusCount: 21882, translation: 'fallen' },
  { id: 'v-vremea', rank: 1027, word: 'vremea', corpusCount: 21877, translation: 'the weather' },
  { id: 'v-câțiva', rank: 1030, word: 'câțiva', corpusCount: 21819, translation: 'a few' },
  { id: 'v-atenție', rank: 1031, word: 'atenție', corpusCount: 21814, translation: 'attention; careful!' },
  { id: 'v-aseară', rank: 1034, word: 'aseară', corpusCount: 21742, translation: 'last night, yesterday evening' },
  { id: 'v-tem', rank: 1036, word: 'tem', corpusCount: 21720, translation: '(mă tem) I\'m afraid' },
  { id: 'v-crescut', rank: 1040, word: 'crescut', corpusCount: 21592, translation: 'grown' },
  { id: 'v-drăguță', rank: 1042, word: 'drăguță', corpusCount: 21562, translation: 'nice, sweet (o)' },
  { id: 'v-conduce', rank: 1046, word: 'conduce', corpusCount: 21452, translation: 'drives; leads' },
  { id: 'v-totdeauna', rank: 1047, word: 'totdeauna', corpusCount: 21446, translation: 'always' },
  { id: 'v-doare', rank: 1048, word: 'doare', corpusCount: 21426, translation: 'hurts' },
  { id: 'v-cină', rank: 1051, word: 'cină', corpusCount: 21346, translation: 'dinner' },
  { id: 'v-imposibil', rank: 1058, word: 'imposibil', corpusCount: 21218, translation: 'impossible' },
  { id: 'v-picioarele', rank: 1061, word: 'picioarele', corpusCount: 21174, translation: 'the legs, the feet' },
  { id: 'v-ajutat', rank: 1062, word: 'ajutat', corpusCount: 21164, translation: 'helped' },
  { id: 'v-serviciu', rank: 1068, word: 'serviciu', corpusCount: 21083, translation: 'work (la serviciu)' },
  { id: 'v-diferit', rank: 1071, word: 'diferit', corpusCount: 20905, translation: 'different' },
  { id: 'v-prinde', rank: 1072, word: 'prinde', corpusCount: 20896, translation: 'catches; catch!' },
  { id: 'v-ajungem', rank: 1074, word: 'ajungem', corpusCount: 20844, translation: 'we arrive' },
  { id: 'v-supărat', rank: 1081, word: 'supărat', corpusCount: 20606, translation: 'upset, cross' },
  { id: 'v-rece', rank: 1089, word: 'rece', corpusCount: 20340, translation: 'cold' },
  { id: 'v-cuvinte', rank: 1091, word: 'cuvinte', corpusCount: 20284, translation: 'words' },
  { id: 'v-trec', rank: 1092, word: 'trec', corpusCount: 20259, translation: 'I pass; (mă trec) I\'ll pop by' },
  { id: 'v-micul', rank: 1093, word: 'micul', corpusCount: 20237, translation: '(micul dejun) breakfast' },
  { id: 'v-periculos', rank: 1098, word: 'periculos', corpusCount: 20210, translation: 'dangerous' },
  { id: 'v-opt', rank: 1099, word: 'opt', corpusCount: 20204, translation: 'eight' },
  { id: 'v-negru', rank: 1105, word: 'negru', corpusCount: 20120, translation: 'black' },
  { id: 'v-merită', rank: 1106, word: 'merită', corpusCount: 20118, translation: 'it\'s worth it' },
  { id: 'v-viitor', rank: 1112, word: 'viitor', corpusCount: 19936, translation: 'future' },
  { id: 'v-mâncat', rank: 1115, word: 'mâncat', corpusCount: 19882, translation: 'eaten' },
  { id: 'v-diseară', rank: 1118, word: 'diseară', corpusCount: 19836, translation: 'this evening' },
  { id: 'v-ăia', rank: 1119, word: 'ăia', corpusCount: 19816, translation: 'those ones' },
  { id: 'v-succes', rank: 1124, word: 'succes', corpusCount: 19668, translation: 'success; good luck!' },
  { id: 'v-indiferent', rank: 1128, word: 'indiferent', corpusCount: 19531, translation: '(mi-e indiferent) I don\'t mind' },
  { id: 'v-câine', rank: 1135, word: 'câine', corpusCount: 19427, translation: 'dog' },
  { id: 'v-încet', rank: 1138, word: 'încet', corpusCount: 19392, translation: 'slowly; quietly' },
  { id: 'v-deși', rank: 1139, word: 'deși', corpusCount: 19370, translation: 'although' },
  { id: 'v-plătit', rank: 1142, word: 'plătit', corpusCount: 19306, translation: 'paid' },
  { id: 'v-felicitări', rank: 1147, word: 'felicitări', corpusCount: 19178, translation: 'congratulations' },
  { id: 'v-incredibil', rank: 1152, word: 'incredibil', corpusCount: 19020, translation: 'incredible' },
  { id: 'v-cumpărat', rank: 1158, word: 'cumpărat', corpusCount: 18978, translation: 'bought' },
  { id: 'v-liniște', rank: 1163, word: 'liniște', corpusCount: 18904, translation: 'quiet, silence' },
  { id: 'v-bere', rank: 1167, word: 'bere', corpusCount: 18840, translation: 'beer' },
  { id: 'v-câți', rank: 1168, word: 'câți', corpusCount: 18831, translation: 'how many' },
  { id: 'v-stăm', rank: 1170, word: 'stăm', corpusCount: 18703, translation: 'we stay; we live' },
  { id: 'v-apropo', rank: 1176, word: 'apropo', corpusCount: 18594, translation: 'by the way' },
  { id: 'v-închide', rank: 1178, word: 'închide', corpusCount: 18570, translation: 'closes; close!' },
  { id: 'v-șapte', rank: 1182, word: 'șapte', corpusCount: 18476, translation: 'seven' },
  { id: 'v-doilea', rank: 1184, word: 'doilea', corpusCount: 18459, translation: '(al doilea) the second' },
  { id: 'v-ușă', rank: 1188, word: 'ușă', corpusCount: 18323, translation: 'door' },
  { id: 'v-trăiesc', rank: 1189, word: 'trăiesc', corpusCount: 18316, translation: 'I live' },
  { id: 'v-păcat', rank: 1192, word: 'păcat', corpusCount: 18220, translation: 'shame, pity (ce păcat!)' },
  { id: 'v-născut', rank: 1194, word: 'născut', corpusCount: 18214, translation: 'born' },
  { id: 'v-trezit', rank: 1195, word: 'trezit', corpusCount: 18175, translation: 'woken up' },
  { id: 'v-deasupra', rank: 1200, word: 'deasupra', corpusCount: 18098, translation: 'above' },
  { id: 'v-atinge', rank: 1202, word: 'atinge', corpusCount: 18075, translation: 'touches; touch!' },
  { id: 'v-glumești', rank: 1213, word: 'glumești', corpusCount: 17931, translation: 'you\'re joking' },
  { id: 'v-exemplu', rank: 1215, word: 'exemplu', corpusCount: 17832, translation: 'example' },
  { id: 'v-întâlnim', rank: 1216, word: 'întâlnim', corpusCount: 17827, translation: '(ne întâlnim) we meet' },
  { id: 'v-joci', rank: 1217, word: 'joci', corpusCount: 17788, translation: '(te joci) you play' },
  { id: 'v-stânga', rank: 1222, word: 'stânga', corpusCount: 17596, translation: 'left' },
  { id: 'v-țară', rank: 1227, word: 'țară', corpusCount: 17480, translation: 'country; (la țară) countryside' },
  { id: 'v-ajută', rank: 1233, word: 'ajută', corpusCount: 17402, translation: 'help!' },
  { id: 'v-bolnav', rank: 1249, word: 'bolnav', corpusCount: 17143, translation: 'ill' },
  { id: 'v-alb', rank: 1250, word: 'alb', corpusCount: 17143, translation: 'white' },
  { id: 'v-următorul', rank: 1253, word: 'următorul', corpusCount: 17119, translation: 'the next' },
  { id: 'v-cadou', rank: 1256, word: 'cadou', corpusCount: 17102, translation: 'present, gift' },
  { id: 'v-magazin', rank: 1262, word: 'magazin', corpusCount: 17029, translation: 'shop' },
  { id: 'v-nicăieri', rank: 1263, word: 'nicăieri', corpusCount: 17014, translation: 'nowhere' },
  { id: 'v-iubire', rank: 1265, word: 'iubire', corpusCount: 17003, translation: 'love' },
  { id: 'v-tânăr', rank: 1275, word: 'tânăr', corpusCount: 16820, translation: 'young' },
  { id: 'v-depinde', rank: 1277, word: 'depinde', corpusCount: 16802, translation: 'it depends' },
  { id: 'v-lungă', rank: 1278, word: 'lungă', corpusCount: 16752, translation: 'long (o)' },
  { id: 'v-grea', rank: 1280, word: 'grea', corpusCount: 16722, translation: 'heavy, hard (o)' },
  { id: 'v-oriunde', rank: 1283, word: 'oriunde', corpusCount: 16666, translation: 'anywhere' },
  { id: 'v-vis', rank: 1287, word: 'vis', corpusCount: 16608, translation: 'dream' },
  { id: 'v-zilele', rank: 1289, word: 'zilele', corpusCount: 16596, translation: 'the days' },
  { id: 'v-singuri', rank: 1290, word: 'singuri', corpusCount: 16592, translation: 'alone (plural)' },
  { id: 'v-respect', rank: 1302, word: 'respect', corpusCount: 16316, translation: 'respect' },
  { id: 'v-adevărată', rank: 1303, word: 'adevărată', corpusCount: 16315, translation: 'true, real (o)' },
  { id: 'v-chestie', rank: 1306, word: 'chestie', corpusCount: 16252, translation: 'thing' },
  { id: 'v-suni', rank: 1307, word: 'suni', corpusCount: 16232, translation: 'you call' },
  { id: 'v-bărbați', rank: 1312, word: 'bărbați', corpusCount: 16165, translation: 'men' },
  { id: 'v-oare', rank: 1320, word: 'oare', corpusCount: 16084, translation: 'I wonder' },
  { id: 'v-cheia', rank: 1327, word: 'cheia', corpusCount: 15927, translation: 'the key' },
  { id: 'v-număr', rank: 1329, word: 'număr', corpusCount: 15850, translation: 'number' },
  { id: 'v-câteodată', rank: 1333, word: 'câteodată', corpusCount: 15805, translation: 'sometimes' },
  { id: 'v-mijlocul', rank: 1334, word: 'mijlocul', corpusCount: 15804, translation: 'the middle' },
  { id: 'v-vorbă', rank: 1338, word: 'vorbă', corpusCount: 15749, translation: 'word, talk' },
  { id: 'v-adresa', rank: 1343, word: 'adresa', corpusCount: 15670, translation: 'the address' },
  { id: 'v-frumoase', rank: 1352, word: 'frumoase', corpusCount: 15553, translation: 'beautiful (plural)' },
  { id: 'v-mulțumim', rank: 1355, word: 'mulțumim', corpusCount: 15522, translation: 'we thank you, thanks' },
  { id: 'v-surpriză', rank: 1370, word: 'surpriză', corpusCount: 15365, translation: 'surprise' },
  { id: 'v-glumă', rank: 1374, word: 'glumă', corpusCount: 15270, translation: 'joke' },
  { id: 'v-părere', rank: 1375, word: 'părere', corpusCount: 15270, translation: 'opinion' },
  { id: 'v-ambele', rank: 1376, word: 'ambele', corpusCount: 15262, translation: 'both (o)' },
  { id: 'v-mișto', rank: 1377, word: 'mișto', corpusCount: 15255, translation: 'cool' },
  { id: 'v-prostii', rank: 1378, word: 'prostii', corpusCount: 15247, translation: 'nonsense' },
  { id: 'v-urmează', rank: 1379, word: 'urmează', corpusCount: 15240, translation: 'follows; comes next' },
  { id: 'v-marea', rank: 1386, word: 'marea', corpusCount: 15180, translation: 'the sea' },
  { id: 'v-ceai', rank: 1389, word: 'ceai', corpusCount: 15160, translation: 'tea' },
  { id: 'v-habar', rank: 1391, word: 'habar', corpusCount: 15136, translation: '(n-am habar) I\'ve no idea' },
  { id: 'v-distractiv', rank: 1393, word: 'distractiv', corpusCount: 15097, translation: 'fun' },
  { id: 'v-des', rank: 1394, word: 'des', corpusCount: 15094, translation: 'often' },
  { id: 'v-curat', rank: 1397, word: 'curat', corpusCount: 15084, translation: 'clean' },
  { id: 'v-oprește', rank: 1398, word: 'oprește', corpusCount: 15058, translation: 'stop!' },
  { id: 'v-stradă', rank: 1401, word: 'stradă', corpusCount: 15036, translation: 'street' },
  { id: 'v-iată', rank: 1405, word: 'iată', corpusCount: 14985, translation: 'here is, behold' },
  { id: 'v-întârziat', rank: 1408, word: 'întârziat', corpusCount: 14943, translation: 'late (been delayed)' },
  { id: 'v-mami', rank: 1409, word: 'mami', corpusCount: 14892, translation: 'Mummy' },
  { id: 'v-mănâncă', rank: 1418, word: 'mănâncă', corpusCount: 14814, translation: 'eats; eat!' },
  { id: 'v-carne', rank: 1434, word: 'carne', corpusCount: 14483, translation: 'meat' },
  { id: 'v-dorm', rank: 1438, word: 'dorm', corpusCount: 14437, translation: 'I sleep' },
  { id: 'v-veche', rank: 1441, word: 'veche', corpusCount: 14418, translation: 'old (o)' },
  { id: 'v-haine', rank: 1443, word: 'haine', corpusCount: 14387, translation: 'clothes' },
  { id: 'v-centrul', rank: 1444, word: 'centrul', corpusCount: 14372, translation: 'the centre' },
  { id: 'v-scurt', rank: 1445, word: 'scurt', corpusCount: 14355, translation: 'short' },
  { id: 'v-vârsta', rank: 1446, word: 'vârsta', corpusCount: 14338, translation: 'the age' },
  { id: 'v-bunica', rank: 1449, word: 'bunica', corpusCount: 14309, translation: 'Grandma' },
  { id: 'v-școala', rank: 1452, word: 'școala', corpusCount: 14295, translation: 'the school' },
  { id: 'v-căsătorit', rank: 1453, word: 'căsătorit', corpusCount: 14271, translation: 'married' },
  { id: 'v-dulce', rank: 1460, word: 'dulce', corpusCount: 14140, translation: 'sweet' },
  { id: 'v-durere', rank: 1469, word: 'durere', corpusCount: 14022, translation: 'pain' },
  { id: 'v-zbor', rank: 1470, word: 'zbor', corpusCount: 14015, translation: 'flight' },
  { id: 'v-dejun', rank: 1495, word: 'dejun', corpusCount: 13746, translation: '(micul dejun) breakfast' },
  { id: 'v-ratat', rank: 1498, word: 'ratat', corpusCount: 13734, translation: 'missed' },
]
