import manifest from './generated/audio-manifest.json'

// Generated by `npm run generate:audio` — maps "<lang>|<exact text>" to a pre-recorded clip.
// Keyed by the exact text so an edited phrase can never play stale audio: it just falls back to
// the built-in voice until the audio is regenerated.
const clips: Record<string, string> = manifest

export function recordedClipUrl(text: string, lang: string): string | undefined {
  const file = clips[`${lang.slice(0, 2)}|${text}`]
  return file ? `${import.meta.env.BASE_URL}${file}` : undefined
}

export const recordedClipCount = Object.keys(clips).length
